In [73]:
# ============================================
# CLOUD KITCHEN INTELLIGENCE PROJECT
# Step 1: Import libraries and set up the project
# ============================================

import pandas as pd
import numpy as np

# Make our random data reproducible
np.random.seed(42)

print("Libraries imported successfully!")
print("Project setup complete.")

Libraries imported successfully!
Project setup complete.

In [74]:
# ============================================
# STEP 2: Create synthetic locality data
# ============================================

localities = pd.DataFrame({
    "locality_id": range(1, 11),

    "locality_name": [
        "Rajpur Road",
        "Jakhan",
        "Clement Town",
        "Prem Nagar",
        "Ballupur",
        "Vasant Vihar",
        "Patel Nagar",
        "Sahastradhara Road",
        "Nehru Colony",
        "Race Course"
    ],

    "zone": [
        "Central",
        "North",
        "South",
        "West",
        "Central",
        "West",
        "Central",
        "East",
        "Central",
        "Central"
    ],

    "population_density": [
        82, 76, 68, 72, 85,
        64, 88, 60, 91, 86
    ],

    "avg_monthly_income": [
        52000, 48000, 36000, 33000, 45000,
        51000, 37000, 47000, 39000, 43000
    ],

    "student_share_pct": [
        12, 15, 28, 32, 18,
        10, 14, 22, 16, 12
    ],

    "office_worker_share_pct": [
        32, 28, 18, 16, 30,
        35, 22, 25, 28, 30
    ],

    "residential_share_pct": [
        42, 45, 38, 36, 40,
        48, 44, 42, 46, 43
    ],

    "tourism_score": [
        85, 78, 45, 35, 62,
        40, 30, 70, 38, 55
    ],

    "competition_score": [
        88, 80, 55, 48, 76,
        52, 58, 64, 70, 73
    ]
})

# Display the first few rows
localities.head()

,locality_id,locality_name,zone,population_density,avg_monthly_income,student_share_pct,office_worker_share_pct,residential_share_pct,tourism_score,competition_score
0,1,Rajpur Road,Central,82,52000,12,32,42,85,88
1,2,Jakhan,North,76,48000,15,28,45,78,80
2,3,Clement Town,South,68,36000,28,18,38,45,55
3,4,Prem Nagar,West,72,33000,32,16,36,35,48
4,5,Ballupur,Central,85,45000,18,30,40,62,76

In [75]:
# ============================================
# STEP 2.2: Create synthetic restaurant data
# ============================================

# Number of restaurants
n_restaurants = 150

# Restaurant IDs
restaurant_ids = [f"R{i:03d}" for i in range(1, n_restaurants + 1)]

# Cuisine categories
cuisines = [
    "North Indian",
    "Chinese",
    "Biryani",
    "Pizza",
    "Burgers",
    "South Indian",
    "Momos",
    "Healthy",
    "Desserts",
    "Cafe"
]

# Generate restaurant data
restaurants = pd.DataFrame({
    "restaurant_id": restaurant_ids,

    # Randomly assign a locality
    "locality_id": np.random.choice(
        localities["locality_id"],
        size=n_restaurants
    ),

    # Randomly assign cuisine
    "cuisine": np.random.choice(
        cuisines,
        size=n_restaurants
    ),

    # Restaurant rating between 3.0 and 4.9
    "rating": np.round(
        np.random.uniform(3.0, 4.9, n_restaurants),
        1
    ),

    # Number of reviews
    "review_count": np.random.randint(
        50, 5001, n_restaurants
    ),

    # Average order value in ₹
    "avg_order_value": np.random.randint(
        150, 701, n_restaurants
    ),

    # Average delivery time in minutes
    "avg_delivery_time_min": np.random.randint(
        20, 61, n_restaurants
    ),

    # Discount offered
    "discount_pct": np.random.choice(
        [0, 5, 10, 15, 20, 25, 30, 40],
        size=n_restaurants
    ),

    # Primary delivery platform
    "platform": np.random.choice(
        ["Swiggy", "Zomato", "Direct"],
        size=n_restaurants,
        p=[0.45, 0.45, 0.10]
    )
})

# Display first 10 restaurants
restaurants.head(10)

,restaurant_id,locality_id,cuisine,rating,review_count,avg_order_value,avg_delivery_time_min,discount_pct,platform
0,R001,7,Biryani,4.8,4182,431,41,20,Swiggy
1,R002,4,Momos,3.6,3901,212,53,20,Zomato
2,R003,8,South Indian,4.1,3490,366,27,10,Swiggy
3,R004,5,Healthy,4.1,3816,610,59,30,Swiggy
4,R005,7,Desserts,4.9,2376,254,38,0,Swiggy
5,R006,10,Burgers,3.1,2964,248,60,25,Zomato
6,R007,3,North Indian,3.6,4002,660,56,15,Direct
7,R008,7,Biryani,3.4,645,534,25,25,Zomato
8,R009,8,Cafe,3.5,778,554,45,5,Zomato
9,R010,5,Healthy,3.9,1415,667,53,5,Zomato

In [76]:
# ============================================
# STEP 2.3: Basic data validation
# ============================================

print("Number of restaurants:", len(restaurants))
print("Number of columns:", len(restaurants.columns))

print("\nMissing values:")
print(restaurants.isnull().sum())

print("\nDuplicate restaurant IDs:")
print(restaurants["restaurant_id"].duplicated().sum())

print("\nCuisine distribution:")
print(restaurants["cuisine"].value_counts())

print("\nPlatform distribution:")
print(restaurants["platform"].value_counts())

Number of restaurants: 150
Number of columns: 9

Missing values:
restaurant_id            0
locality_id              0
cuisine                  0
rating                   0
review_count             0
avg_order_value          0
avg_delivery_time_min    0
discount_pct             0
platform                 0
dtype: int64

Duplicate restaurant IDs:
0

Cuisine distribution:
cuisine
North Indian    25
Biryani         21
Pizza           17
South Indian    17
Healthy         16
Desserts        13
Momos           12
Chinese         12
Burgers         11
Cafe             6
Name: count, dtype: int64

Platform distribution:
platform
Zomato    77
Swiggy    59
Direct    14
Name: count, dtype: int64

In [77]:
# ============================================
# STEP 2.4: Add estimated monthly orders
# ============================================

# Cuisine popularity weights
cuisine_demand = {
    "North Indian": 1.20,
    "Biryani": 1.25,
    "Chinese": 1.15,
    "Pizza": 1.10,
    "Burgers": 1.05,
    "South Indian": 0.95,
    "Momos": 1.10,
    "Healthy": 0.85,
    "Desserts": 0.90,
    "Cafe": 0.95
}

# Get demand factor for each restaurant's cuisine
restaurants["cuisine_factor"] = restaurants["cuisine"].map(cuisine_demand)

# Calculate a base demand score
restaurants["demand_score"] = (
    restaurants["rating"] * 25
    + restaurants["review_count"] / 200
    + restaurants["discount_pct"] * 1.5
    + (60 - restaurants["avg_delivery_time_min"]) * 2
    + restaurants["cuisine_factor"] * 20
)

# Convert demand score into estimated monthly orders
restaurants["estimated_monthly_orders"] = (
    restaurants["demand_score"] * 8
).round().astype(int)

# Make sure orders don't become unrealistically low
restaurants["estimated_monthly_orders"] = (
    restaurants["estimated_monthly_orders"].clip(lower=100)
)

# Display the result
restaurants[
    [
        "restaurant_id",
        "cuisine",
        "rating",
        "avg_delivery_time_min",
        "discount_pct",
        "estimated_monthly_orders"
    ]
].head(10)

,restaurant_id,cuisine,rating,avg_delivery_time_min,discount_pct,estimated_monthly_orders
0,R001,Biryani,4.8,41,20,1871
1,R002,Momos,3.6,53,20,1404
2,R003,South Indian,4.1,27,10,1760
3,R004,Healthy,4.1,59,30,1485
4,R005,Desserts,4.9,38,0,1571
5,R006,Burgers,3.1,60,25,1207
6,R007,North Indian,3.6,56,15,1316
7,R008,Biryani,3.4,25,25,1766
8,R009,Cafe,3.5,45,5,1183
9,R010,Healthy,3.9,53,5,1145

In [78]:
# Remove temporary calculation columns
restaurants.drop(
    columns=["cuisine_factor", "demand_score"],
    inplace=True
)

# Check our final restaurant structure
print("Columns in Restaurants table:")
print(restaurants.columns.tolist())

print("\nNumber of restaurants:", len(restaurants))

Columns in Restaurants table:
['restaurant_id', 'locality_id', 'cuisine', 'rating', 'review_count', 'avg_order_value', 'avg_delivery_time_min', 'discount_pct', 'platform', 'estimated_monthly_orders']

Number of restaurants: 150

In [79]:
# ============================================
# STEP 3.1: Define menu items by cuisine
# ============================================

menu_by_cuisine = {

    "North Indian": [
        ("Butter Chicken", "Main Course", 280, "Non-Veg", 25),
        ("Paneer Butter Masala", "Main Course", 220, "Veg", 20),
        ("Dal Makhani", "Main Course", 180, "Veg", 18),
        ("Chole Bhature", "Main Course", 160, "Veg", 15),
        ("Kadhai Paneer", "Main Course", 210, "Veg", 20),
        ("Chicken Tikka", "Starter", 240, "Non-Veg", 20),
        ("Paneer Tikka", "Starter", 200, "Veg", 18),
        ("Garlic Naan", "Bread", 70, "Veg", 8),
        ("Jeera Rice", "Rice", 130, "Veg", 15),
        ("Gulab Jamun", "Dessert", 90, "Veg", 8)
    ],

    "Biryani": [
        ("Chicken Biryani", "Main Course", 220, "Non-Veg", 25),
        ("Mutton Biryani", "Main Course", 320, "Non-Veg", 30),
        ("Egg Biryani", "Main Course", 180, "Non-Veg", 22),
        ("Paneer Biryani", "Main Course", 190, "Veg", 22),
        ("Veg Biryani", "Main Course", 160, "Veg", 20),
        ("Chicken 65", "Starter", 210, "Non-Veg", 18),
        ("Raita", "Side", 60, "Veg", 5),
        ("Biryani Combo", "Combo", 280, "Non-Veg", 28)
    ],

    "Chinese": [
        ("Veg Hakka Noodles", "Main Course", 160, "Veg", 15),
        ("Chicken Hakka Noodles", "Main Course", 210, "Non-Veg", 18),
        ("Veg Fried Rice", "Main Course", 150, "Veg", 15),
        ("Chicken Fried Rice", "Main Course", 200, "Non-Veg", 18),
        ("Chilli Paneer", "Starter", 190, "Veg", 15),
        ("Chilli Chicken", "Starter", 220, "Non-Veg", 18),
        ("Manchurian", "Starter", 170, "Veg", 15),
        ("Spring Rolls", "Starter", 130, "Veg", 12)
    ],

    "Pizza": [
        ("Margherita Pizza", "Main Course", 220, "Veg", 15),
        ("Farmhouse Pizza", "Main Course", 320, "Veg", 18),
        ("Paneer Pizza", "Main Course", 300, "Veg", 18),
        ("Chicken Pizza", "Main Course", 350, "Non-Veg", 20),
        ("Pepperoni Pizza", "Main Course", 380, "Non-Veg", 20),
        ("Garlic Bread", "Side", 140, "Veg", 10),
        ("Cheese Burst Pizza", "Main Course", 360, "Veg", 20)
    ],

    "Burgers": [
        ("Veg Burger", "Main Course", 130, "Veg", 10),
        ("Paneer Burger", "Main Course", 170, "Veg", 12),
        ("Chicken Burger", "Main Course", 190, "Non-Veg", 12),
        ("Cheese Burger", "Main Course", 180, "Veg", 12),
        ("Double Chicken Burger", "Main Course", 260, "Non-Veg", 15),
        ("French Fries", "Side", 110, "Veg", 8),
        ("Peri Peri Fries", "Side", 130, "Veg", 8)
    ],

    "South Indian": [
        ("Masala Dosa", "Main Course", 120, "Veg", 12),
        ("Plain Dosa", "Main Course", 90, "Veg", 10),
        ("Idli Sambar", "Main Course", 90, "Veg", 10),
        ("Vada Sambar", "Main Course", 100, "Veg", 10),
        ("Paneer Dosa", "Main Course", 150, "Veg", 14),
        ("Uttapam", "Main Course", 120, "Veg", 12),
        ("Filter Coffee", "Beverage", 70, "Veg", 5)
    ],

    "Momos": [
        ("Veg Momos", "Main Course", 120, "Veg", 10),
        ("Chicken Momos", "Main Course", 150, "Non-Veg", 12),
        ("Paneer Momos", "Main Course", 140, "Veg", 12),
        ("Fried Momos", "Main Course", 160, "Veg", 14),
        ("Chicken Fried Momos", "Main Course", 190, "Non-Veg", 15),
        ("Tandoori Momos", "Main Course", 180, "Veg", 15),
        ("Chilli Momos", "Main Course", 170, "Veg", 14)
    ],

    "Healthy": [
        ("Veg Salad Bowl", "Healthy", 180, "Veg", 10),
        ("Chicken Salad Bowl", "Healthy", 230, "Non-Veg", 12),
        ("Paneer Bowl", "Healthy", 220, "Veg", 12),
        ("Grilled Chicken Bowl", "Healthy", 260, "Non-Veg", 18),
        ("Fruit Bowl", "Healthy", 150, "Veg", 8),
        ("Protein Smoothie", "Beverage", 180, "Veg", 8),
        ("Oats Bowl", "Breakfast", 140, "Veg", 10)
    ],

    "Desserts": [
        ("Gulab Jamun", "Dessert", 90, "Veg", 8),
        ("Brownie", "Dessert", 140, "Veg", 10),
        ("Chocolate Cake", "Dessert", 160, "Veg", 12),
        ("Cheesecake", "Dessert", 220, "Veg", 15),
        ("Ice Cream", "Dessert", 100, "Veg", 5),
        ("Chocolate Mousse", "Dessert", 150, "Veg", 10),
        ("Rasmalai", "Dessert", 120, "Veg", 8)
    ],

    "Cafe": [
        ("Cold Coffee", "Beverage", 130, "Veg", 7),
        ("Cappuccino", "Beverage", 120, "Veg", 6),
        ("Masala Tea", "Beverage", 70, "Veg", 5),
        ("Veg Sandwich", "Snack", 140, "Veg", 10),
        ("Paneer Sandwich", "Snack", 170, "Veg", 12),
        ("Cheese Sandwich", "Snack", 160, "Veg", 10),
        ("Chocolate Brownie", "Dessert", 150, "Veg", 10),
        ("Pasta", "Main Course", 200, "Veg", 15)
    ]
}

print("Number of cuisines:", len(menu_by_cuisine))

for cuisine, items in menu_by_cuisine.items():
    print(cuisine, "→", len(items), "items")

Number of cuisines: 10
North Indian → 10 items
Biryani → 8 items
Chinese → 8 items
Pizza → 7 items
Burgers → 7 items
South Indian → 7 items
Momos → 7 items
Healthy → 7 items
Desserts → 7 items
Cafe → 8 items

In [80]:
# ============================================
# STEP 3.2: Generate Menu Items
# ============================================

import pandas as pd
import numpy as np

menu_rows = []

item_counter = 1

for _, restaurant in restaurants.iterrows():

    restaurant_id = restaurant["restaurant_id"]
    cuisine = restaurant["cuisine"]

    # Get menu for this restaurant's cuisine
    menu = menu_by_cuisine[cuisine]

    for item in menu:

        item_name, category, base_price, veg_flag, prep_time = item

        # Small realistic price variation between restaurants
        price_variation = np.random.uniform(0.90, 1.15)

        final_price = round(base_price * price_variation)

        # Popularity score from 1 to 100
        popularity_score = np.random.randint(30, 101)

        menu_rows.append({
            "item_id": f"I{item_counter:04d}",
            "restaurant_id": restaurant_id,
            "cuisine": cuisine,
            "item_name": item_name,
            "category": category,
            "price": final_price,
            "veg_flag": veg_flag,
            "prep_time_min": prep_time,
            "popularity_score": popularity_score
        })

        item_counter += 1


# Create DataFrame
menu_items = pd.DataFrame(menu_rows)

# Display first 10 rows
menu_items.head(10)

,item_id,restaurant_id,cuisine,item_name,category,price,veg_flag,prep_time_min,popularity_score
0,I0001,R001,Biryani,Chicken Biryani,Main Course,231,Non-Veg,25,54
1,I0002,R001,Biryani,Mutton Biryani,Main Course,308,Non-Veg,30,32
2,I0003,R001,Biryani,Egg Biryani,Main Course,165,Non-Veg,22,73
3,I0004,R001,Biryani,Paneer Biryani,Main Course,217,Veg,22,41
4,I0005,R001,Biryani,Veg Biryani,Main Course,158,Veg,20,73
5,I0006,R001,Biryani,Chicken 65,Starter,231,Non-Veg,18,78
6,I0007,R001,Biryani,Raita,Side,56,Veg,5,86
7,I0008,R001,Biryani,Biryani Combo,Combo,283,Non-Veg,28,76
8,I0009,R002,Momos,Veg Momos,Main Course,111,Veg,10,37
9,I0010,R002,Momos,Chicken Momos,Main Course,159,Non-Veg,12,99

In [81]:
# ============================================
# STEP 3.3: Validate Menu Items
# ============================================

print("Number of menu items:", len(menu_items))
print("Number of columns:", len(menu_items.columns))

print("\nMissing values:")
print(menu_items.isnull().sum())

print("\nDuplicate item IDs:")
print(menu_items["item_id"].duplicated().sum())

print("\nUnique restaurants with menu items:")
print(menu_items["restaurant_id"].nunique())

print("\nCategory distribution:")
print(menu_items["category"].value_counts())

print("\nVeg / Non-Veg distribution:")
print(menu_items["veg_flag"].value_counts())

print("\nPrice summary:")
print(menu_items["price"].describe())

Number of menu items: 1164
Number of columns: 9

Missing values:
item_id             0
restaurant_id       0
cuisine             0
item_name           0
category            0
price               0
veg_flag            0
prep_time_min       0
popularity_score    0
dtype: int64

Duplicate item IDs:
0

Unique restaurants with menu items:
150

Category distribution:
category
Main Course    627
Dessert        122
Starter        119
Healthy         80
Side            60
Beverage        51
Bread           25
Rice            25
Combo           21
Snack           18
Breakfast       16
Name: count, dtype: int64

Veg / Non-Veg distribution:
veg_flag
Veg        861
Non-Veg    303
Name: count, dtype: int64

Price summary:
count    1164.000000
mean      184.957904
std        74.616618
min        54.000000
25%       135.000000
50%       174.000000
75%       220.000000
max       436.000000
Name: price, dtype: float64

In [82]:
# ============================================
# STEP 4.1: Create Order Date Framework
# ============================================

import pandas as pd
import numpy as np

# Set seed so our synthetic data is reproducible
np.random.seed(42)

# Date range: one full year
start_date = "2025-01-01"
end_date = "2025-12-31"

date_range = pd.date_range(
    start=start_date,
    end=end_date,
    freq="D"
)

print("Start date:", date_range.min())
print("End date:", date_range.max())
print("Number of days:", len(date_range))

Start date: 2025-01-01 00:00:00
End date: 2025-12-31 00:00:00
Number of days: 365

In [83]:
# ============================================
# STEP 4.2: Define Ordering-Time Demand
# ============================================

# Hours from 7 AM to 11 PM
hours = np.arange(7, 24)

# Demand weight for each hour
# Higher number = more likely to receive an order
hour_weights = {
    7:  0.5,
    8:  0.7,
    9:  0.8,
    10: 0.6,
    11: 0.8,
    12: 1.4,
    13: 1.7,
    14: 1.5,
    15: 0.8,
    16: 0.6,
    17: 0.8,
    18: 1.0,
    19: 1.5,
    20: 1.9,
    21: 2.0,
    22: 1.7,
    23: 1.0
}

# Convert weights into probabilities
weights = np.array([hour_weights[h] for h in hours])
hour_probabilities = weights / weights.sum()

# Display the distribution
time_demand = pd.DataFrame({
    "hour": hours,
    "demand_weight": weights,
    "probability": hour_probabilities
})

time_demand

    hour  demand_weight  probability
0      7            0.5     0.025907
1      8            0.7     0.036269
2      9            0.8     0.041451
3     10            0.6     0.031088
4     11            0.8     0.041451
5     12            1.4     0.072539
6     13            1.7     0.088083
7     14            1.5     0.077720
8     15            0.8     0.041451
9     16            0.6     0.031088
10    17            0.8     0.041451
11    18            1.0     0.051813
12    19            1.5     0.077720
13    20            1.9     0.098446
14    21            2.0     0.103627
15    22            1.7     0.088083
16    23            1.0     0.051813

In [84]:
# ============================================
# STEP 4.3: Define Weekday vs Weekend Demand
# ============================================

day_weights = {
    0: 0.90,   # Monday
    1: 0.95,   # Tuesday
    2: 1.00,   # Wednesday
    3: 1.00,   # Thursday
    4: 1.15,   # Friday
    5: 1.35,   # Saturday
    6: 1.25    # Sunday
}

day_names = [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday"
]

day_demand = pd.DataFrame({
    "day_of_week": day_names,
    "demand_weight": [
        day_weights[i] for i in range(7)
    ]
})

day_demand

  day_of_week  demand_weight
0      Monday           0.90
1     Tuesday           0.95
2   Wednesday           1.00
3    Thursday           1.00
4      Friday           1.15
5    Saturday           1.35
6      Sunday           1.25

In [85]:
# ============================================
# STEP 4.4: Define Customer Segments
# ============================================

customer_segments = {

    "Student": {
        "weight": 0.30,
        "avg_order_value": 220,
        "preferred_hours": [18, 19, 20, 21, 22, 23]
    },

    "Working Professional": {
        "weight": 0.30,
        "avg_order_value": 350,
        "preferred_hours": [12, 13, 14, 19, 20, 21]
    },

    "Family": {
        "weight": 0.20,
        "avg_order_value": 500,
        "preferred_hours": [12, 13, 14, 19, 20, 21]
    },

    "Young Professional": {
        "weight": 0.20,
        "avg_order_value": 400,
        "preferred_hours": [18, 19, 20, 21, 22]
    }
}

# Display the customer segments
for segment, details in customer_segments.items():
    print(
        segment,
        "→ Weight:", details["weight"],
        "| Avg AOV: ₹", details["avg_order_value"],
        "| Preferred hours:", details["preferred_hours"]
    )

Student → Weight: 0.3 | Avg AOV: ₹ 220 | Preferred hours: [18, 19, 20, 21, 22, 23]
Working Professional → Weight: 0.3 | Avg AOV: ₹ 350 | Preferred hours: [12, 13, 14, 19, 20, 21]
Family → Weight: 0.2 | Avg AOV: ₹ 500 | Preferred hours: [12, 13, 14, 19, 20, 21]
Young Professional → Weight: 0.2 | Avg AOV: ₹ 400 | Preferred hours: [18, 19, 20, 21, 22]

In [86]:
# ============================================
# STEP 4.5: Generate Synthetic Customers
# ============================================

np.random.seed(42)

n_customers = 5000

customer_ids = [
    f"C{i:05d}" for i in range(1, n_customers + 1)
]

segments = list(customer_segments.keys())
segment_weights = [
    customer_segments[s]["weight"]
    for s in segments
]

age_groups = ["18-25", "26-35", "36-45", "46-55", "56+"]

customers = pd.DataFrame({
    "customer_id": customer_ids,

    # Assign customer to a locality
    "locality_id": np.random.choice(
        localities["locality_id"],
        size=n_customers
    ),

    # Assign customer segment
    "customer_segment": np.random.choice(
        segments,
        size=n_customers,
        p=segment_weights
    ),

    # Assign age group
    "age_group": np.random.choice(
        age_groups,
        size=n_customers,
        p=[0.30, 0.35, 0.18, 0.12, 0.05]
    ),

    # Assign preferred cuisine
    "preferred_cuisine": np.random.choice(
        cuisines,
        size=n_customers
    )
})

# Display first 10 customers
customers.head(10)

  customer_id  locality_id      customer_segment age_group preferred_cuisine
0      C00001            7                Family     26-35          Desserts
1      C00002            4  Working Professional     26-35              Cafe
2      C00003            8               Student     18-25           Healthy
3      C00004            5               Student     18-25      South Indian
4      C00005            7               Student     18-25              Cafe
5      C00006           10    Young Professional     36-45           Biryani
6      C00007            3  Working Professional     46-55           Chinese
7      C00008            7                Family     26-35             Momos
8      C00009            8  Working Professional     26-35           Healthy
9      C00010            5  Working Professional     26-35              Cafe

In [87]:
# ============================================
# STEP 4.6: Validate Customer Data
# ============================================

print("Number of customers:", len(customers))
print("Number of columns:", len(customers.columns))

print("\nMissing values:")
print(customers.isnull().sum())

print("\nDuplicate customer IDs:")
print(customers["customer_id"].duplicated().sum())

print("\nCustomer segment distribution:")
print(customers["customer_segment"].value_counts())

print("\nAge group distribution:")
print(customers["age_group"].value_counts())

print("\nPreferred cuisine distribution:")
print(customers["preferred_cuisine"].value_counts())

Number of customers: 5000
Number of columns: 5

Missing values:
customer_id          0
locality_id          0
customer_segment     0
age_group            0
preferred_cuisine    0
dtype: int64

Duplicate customer IDs:
0

Customer segment distribution:
customer_segment
Student                 1518
Working Professional    1455
Family                  1025
Young Professional      1002
Name: count, dtype: int64

Age group distribution:
age_group
26-35    1764
18-25    1484
36-45     916
46-55     594
56+       242
Name: count, dtype: int64

Preferred cuisine distribution:
preferred_cuisine
South Indian    525
Cafe            516
North Indian    514
Chinese         506
Momos           503
Desserts        502
Pizza           501
Biryani         497
Healthy         484
Burgers         452
Name: count, dtype: int64

In [88]:
# ============================================
# STEP 4.7: Improve Cuisine Preferences
# ============================================

# Cuisine preferences by customer segment
segment_cuisine_preferences = {

    "Student": {
        "Momos": 0.20,
        "Chinese": 0.18,
        "Burgers": 0.15,
        "Biryani": 0.15,
        "Pizza": 0.12,
        "Cafe": 0.08,
        "South Indian": 0.05,
        "North Indian": 0.04,
        "Desserts": 0.02,
        "Healthy": 0.01
    },

    "Working Professional": {
        "North Indian": 0.20,
        "Biryani": 0.18,
        "Chinese": 0.15,
        "Healthy": 0.12,
        "Pizza": 0.10,
        "Cafe": 0.08,
        "South Indian": 0.07,
        "Momos": 0.05,
        "Desserts": 0.03,
        "Burgers": 0.02
    },

    "Family": {
        "North Indian": 0.25,
        "Biryani": 0.20,
        "Pizza": 0.15,
        "Chinese": 0.12,
        "South Indian": 0.10,
        "Desserts": 0.07,
        "Cafe": 0.04,
        "Momos": 0.03,
        "Healthy": 0.02,
        "Burgers": 0.02
    },

    "Young Professional": {
        "Pizza": 0.18,
        "Chinese": 0.17,
        "Burgers": 0.15,
        "Cafe": 0.12,
        "Biryani": 0.12,
        "Momos": 0.10,
        "North Indian": 0.06,
        "Healthy": 0.04,
        "Desserts": 0.03,
        "South Indian": 0.03
    }
}


# Assign cuisine preferences based on customer segment
for segment in segment_cuisine_preferences:

    mask = customers["customer_segment"] == segment

    preferences = segment_cuisine_preferences[segment]

    customers.loc[mask, "preferred_cuisine"] = np.random.choice(
        list(preferences.keys()),
        size=mask.sum(),
        p=list(preferences.values())
    )


print("Cuisine preferences updated successfully!")

print("\nCuisine preference by customer segment:")
print(
    pd.crosstab(
        customers["customer_segment"],
        customers["preferred_cuisine"],
        normalize="index"
    ).round(2)
)

Cuisine preferences updated successfully!

Cuisine preference by customer segment:
preferred_cuisine     Biryani  Burgers  Cafe  Chinese  Desserts  Healthy  \
customer_segment
Family                   0.17     0.02  0.04     0.13      0.07     0.02
Student                  0.14     0.15  0.07     0.17      0.02     0.02
Working Professional     0.19     0.02  0.07     0.16      0.03     0.12
Young Professional       0.14     0.15  0.11     0.15      0.03     0.05

preferred_cuisine     Momos  North Indian  Pizza  South Indian
customer_segment
Family                 0.03          0.26   0.15          0.11
Student                0.20          0.04   0.14          0.06
Working Professional   0.05          0.18   0.10          0.08
Young Professional     0.11          0.07   0.15          0.04

In [89]:
# ============================================
# STEP 4.8.1: Assign Customer Order Frequency
# ============================================

# Reproducibility
np.random.seed(42)

# Customer frequency categories
frequency_categories = [
    "Occasional",
    "Regular",
    "Frequent"
]

frequency_weights = [
    0.50,   # 50% occasional
    0.35,   # 35% regular
    0.15    # 15% frequent
]

customers["order_frequency"] = np.random.choice(
    frequency_categories,
    size=len(customers),
    p=frequency_weights
)

# Display distribution
print("Customer order frequency distribution:")
print(
    customers["order_frequency"]
    .value_counts()
)

Customer order frequency distribution:
order_frequency
Occasional    2500
Regular       1770
Frequent       730
Name: count, dtype: int64

In [90]:
# ============================================
# STEP 4.8.2: Create Customer Order Weights
# ============================================

# Give each customer an order-generation weight
frequency_weights_map = {
    "Occasional": 1,
    "Regular": 2,
    "Frequent": 4
}

customers["order_weight"] = (
    customers["order_frequency"]
    .map(frequency_weights_map)
)

# Normalize weights so they can be used as probabilities
customers["order_probability"] = (
    customers["order_weight"]
    / customers["order_weight"].sum()
)

print("Total probability:",
      customers["order_probability"].sum())

print("\nOrder probability by customer type:")

print(
    customers.groupby("order_frequency")[
        "order_probability"
    ].sum()
)

Total probability: 1.0

Order probability by customer type:
order_frequency
Frequent      0.325893
Occasional    0.279018
Regular       0.395089
Name: order_probability, dtype: float64

In [91]:
# ============================================
# STEP 4.8.3: Generate Order Dates
# ============================================

np.random.seed(42)

# Target number of orders
n_orders = 30000

# Convert dates into a DataFrame
date_df = pd.DataFrame({
    "order_date": date_range
})

# Get day of week
date_df["day_number"] = date_df["order_date"].dt.dayofweek

# Assign demand weight to each date
date_df["day_weight"] = date_df["day_number"].map(day_weights)

# Convert weights into probabilities
date_probabilities = (
    date_df["day_weight"]
    / date_df["day_weight"].sum()
)

# Randomly select dates for orders
order_dates = np.random.choice(
    date_df["order_date"],
    size=n_orders,
    p=date_probabilities
)

# Check generated dates
print("Number of order dates generated:", len(order_dates))
print("Earliest order date:", order_dates.min())
print("Latest order date:", order_dates.max())

Number of order dates generated: 30000
Earliest order date: 2025-01-01T00:00:00.000000000
Latest order date: 2025-12-31T00:00:00.000000000

In [92]:
# ============================================
# STEP 4.8.4: Generate Order Times
# ============================================

np.random.seed(42)

# Generate an hour for every order
order_hours = np.random.choice(
    hours,
    size=n_orders,
    p=hour_probabilities
)

# Add minutes randomly within the hour
order_minutes = np.random.randint(
    0, 60, size=n_orders
)

# Create the order time
order_times = [
    f"{hour:02d}:{minute:02d}:00"
    for hour, minute in zip(order_hours, order_minutes)
]

# Check the generated times
print("Number of order times generated:", len(order_times))

print("\nSample order times:")
print(order_times[:10])

Number of order times generated: 30000

Sample order times:
['14:12:00', '23:26:00', '20:37:00', '19:32:00', '11:05:00', '11:12:00', '08:12:00', '22:12:00', '19:19:00', '20:35:00']

In [93]:
# ============================================
# STEP 4.8.5: Calculate Restaurant Selection Weights
# ============================================

np.random.seed(42)

# Start with the restaurant's estimated demand
restaurant_weights = restaurants["estimated_monthly_orders"].astype(float).copy()

# Rating effect
restaurant_weights *= (
    restaurants["rating"] / restaurants["rating"].mean()
)

# Discount effect
restaurant_weights *= (
    1 + restaurants["discount_pct"] / 200
)

# Faster delivery gets a small advantage
delivery_factor = (
    restaurants["avg_delivery_time_min"].mean()
    / restaurants["avg_delivery_time_min"]
)

restaurant_weights *= delivery_factor

# Make sure all weights are positive
restaurant_weights = restaurant_weights.clip(lower=0.01)

# Convert to probabilities
restaurant_probabilities = (
    restaurant_weights / restaurant_weights.sum()
)

print("Total restaurant probability:",
      restaurant_probabilities.sum())

print("\nHighest-weight restaurants:")

print(
    restaurants[
        ["restaurant_id", "cuisine", "rating",
         "estimated_monthly_orders"]
    ]
    .assign(selection_probability=restaurant_probabilities)
    .sort_values(
        "selection_probability",
        ascending=False
    )
    .head(10)
)

Total restaurant probability: 0.9999999999999999

Highest-weight restaurants:
    restaurant_id       cuisine  rating  estimated_monthly_orders  \
55           R056         Pizza     4.6                      2105
95           R096       Healthy     4.5                      2052
73           R074       Chinese     4.7                      2124
130          R131  South Indian     4.2                      2089
112          R113  South Indian     4.6                      2045
75           R076          Cafe     3.5                      2122
24           R025       Healthy     4.1                      2044
136          R137       Chinese     4.3                      2096
36           R037       Burgers     4.7                      1995
23           R024  North Indian     4.3                      2226

     selection_probability
55                0.018251
95                0.017405
73                0.017124
130               0.016100
112               0.015761
75                0.014932
24                0.014679
136               0.014496
36                0.014343
23                0.013746

In [94]:
# ============================================
# STEP 4.8.6: Create Customer-Restaurant Matching
# ============================================

# Create a lookup table for restaurant information
restaurant_lookup = restaurants[
    [
        "restaurant_id",
        "locality_id",
        "cuisine",
        "rating",
        "estimated_monthly_orders",
        "avg_delivery_time_min",
        "discount_pct"
    ]
].copy()

# Base restaurant score
restaurant_lookup["base_score"] = (
    restaurant_lookup["estimated_monthly_orders"]
    * (restaurant_lookup["rating"] / restaurants["rating"].mean())
)

# Create a function to calculate restaurant probabilities
def get_restaurant_probabilities(customer_locality, preferred_cuisine):

    scores = restaurant_lookup["base_score"].copy()

    # Same locality gets a strong boost
    scores = scores * np.where(
        restaurant_lookup["locality_id"] == customer_locality,
        3.0,
        0.5
    )

    # Preferred cuisine gets a strong boost
    scores = scores * np.where(
        restaurant_lookup["cuisine"] == preferred_cuisine,
        3.0,
        0.7
    )

    # Faster delivery gets a small advantage
    delivery_factor = (
        restaurant_lookup["avg_delivery_time_min"].mean()
        / restaurant_lookup["avg_delivery_time_min"]
    )

    scores = scores * delivery_factor

    # Discount gets a small advantage
    scores = scores * (
        1 + restaurant_lookup["discount_pct"] / 200
    )

    # Convert scores into probabilities
    probabilities = scores / scores.sum()

    return probabilities.values


# Test the matching for the first customer
test_customer = customers.iloc[0]

test_probabilities = get_restaurant_probabilities(
    test_customer["locality_id"],
    test_customer["preferred_cuisine"]
)

# Show top 5 restaurant choices for this customer
test_results = restaurant_lookup[
    ["restaurant_id", "locality_id", "cuisine"]
].copy()

test_results["probability"] = test_probabilities

test_results = test_results.sort_values(
    "probability",
    ascending=False
).head(5)

print("Test customer:")
print(test_customer[
    ["customer_id", "locality_id",
     "customer_segment", "preferred_cuisine"]
])

print("\nMost likely restaurants:")
print(test_results)

Test customer:
customer_id          C00001
locality_id               7
customer_segment     Family
preferred_cuisine     Pizza
Name: 0, dtype: object

Most likely restaurants:
    restaurant_id  locality_id  cuisine  probability
117          R118            7    Pizza     0.083962
80           R081            7    Pizza     0.080719
55           R056            4    Pizza     0.036323
7            R008            7  Biryani     0.025226
17           R018            8    Pizza     0.023428

In [95]:
# ============================================
# STEP 4.8.7: Assign Restaurants to Orders
# ============================================

np.random.seed(42)

# Randomly select customers for each order
selected_customer_indices = np.random.choice(
    customers.index,
    size=n_orders,
    p=customers["order_probability"]
)

# Get the selected customer records
selected_customers = customers.loc[
    selected_customer_indices
].reset_index(drop=True)

# Store customer IDs
order_customer_ids = selected_customers["customer_id"].values

# Store customer localities
order_localities = selected_customers["locality_id"].values

# Store customer segments
order_segments = selected_customers["customer_segment"].values

# Store preferred cuisines
order_preferred_cuisines = selected_customers["preferred_cuisine"].values


# --------------------------------------------
# Function to select a restaurant
# --------------------------------------------

def select_restaurant(locality, preferred_cuisine):

    # Start with base restaurant score
    scores = restaurant_lookup["base_score"].copy()

    # Same locality
    scores *= np.where(
        restaurant_lookup["locality_id"] == locality,
        3.0,
        0.5
    )

    # Preferred cuisine
    scores *= np.where(
        restaurant_lookup["cuisine"] == preferred_cuisine,
        3.0,
        0.7
    )

    # Delivery speed
    scores *= (
        restaurant_lookup["avg_delivery_time_min"].mean()
        / restaurant_lookup["avg_delivery_time_min"]
    )

    # Discount
    scores *= (
        1 + restaurant_lookup["discount_pct"] / 200
    )

    # Convert to probabilities
    probabilities = scores / scores.sum()

    # Select restaurant
    return np.random.choice(
        restaurant_lookup["restaurant_id"],
        p=probabilities
    )


# Select restaurants for all orders
order_restaurant_ids = [
    select_restaurant(locality, cuisine)
    for locality, cuisine
    in zip(
        order_localities,
        order_preferred_cuisines
    )
]


# Check results
print("Restaurants assigned:", len(order_restaurant_ids))

print("\nFirst 10 restaurant assignments:")
print(order_restaurant_ids[:10])

Restaurants assigned: 30000

First 10 restaurant assignments:
['R080', 'R056', 'R149', 'R045', 'R079', 'R100', 'R123', 'R067', 'R104', 'R055']

In [96]:
# ============================================
# STEP 4.8.8: Select Menu Items for Orders
# ============================================

np.random.seed(42)

# Create a quick lookup of menu items by restaurant
restaurant_menu = {}

for restaurant_id, group in menu_items.groupby("restaurant_id"):

    restaurant_menu[restaurant_id] = {
        "item_ids": group["item_id"].values,
        "popularity": group["popularity_score"].values
    }


# --------------------------------------------
# Function to select an item from a restaurant
# --------------------------------------------

def select_menu_item(restaurant_id):

    menu = restaurant_menu[restaurant_id]

    # Use popularity score as selection weight
    weights = menu["popularity"].astype(float)

    # Convert to probabilities
    probabilities = weights / weights.sum()

    # Select an item
    return np.random.choice(
        menu["item_ids"],
        p=probabilities
    )


# --------------------------------------------
# Select item for every order
# --------------------------------------------

order_item_ids = [
    select_menu_item(restaurant_id)
    for restaurant_id in order_restaurant_ids
]


# --------------------------------------------
# Check results
# --------------------------------------------

print("Menu items assigned:", len(order_item_ids))

print("\nFirst 10 item assignments:")
print(order_item_ids[:10])

Menu items assigned: 30000

First 10 item assignments:
['I0617', 'I0438', 'I1155', 'I0353', 'I0607', 'I0770', 'I0944', 'I0522', 'I0802', 'I0429']

In [97]:
# ============================================
# STEP 4.8.9: Assign Ordering Platform
# ============================================

# Platform probabilities
platform_options = ["Zomato", "Swiggy", "Direct"]

platform_probabilities = [0.45, 0.45, 0.10]

# Generate platform for every order
order_platforms = np.random.choice(
    platform_options,
    size=n_orders,
    p=platform_probabilities
)

# Check results
print("Platforms assigned:", len(order_platforms))

print("\nPlatform distribution:")
print(
    pd.Series(order_platforms)
    .value_counts()
)

print("\nPlatform percentage:")
print(
    pd.Series(order_platforms)
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

Platforms assigned: 30000

Platform distribution:
Zomato    13517
Swiggy    13493
Direct     2990
Name: count, dtype: int64

Platform percentage:
Zomato    45.06
Swiggy    44.98
Direct     9.97
Name: proportion, dtype: float64

In [98]:
# ============================================
# STEP 4.8.10A: Get Item Details for Orders
# ============================================

# Create a lookup table for menu items
item_lookup = menu_items[
    [
        "item_id",
        "restaurant_id",
        "cuisine",
        "item_name",
        "category",
        "price",
        "veg_flag",
        "prep_time_min",
        "popularity_score"
    ]
].copy()

# Match each selected item to its details
selected_items = pd.DataFrame({
    "item_id": order_item_ids
})

selected_items = selected_items.merge(
    item_lookup,
    on="item_id",
    how="left"
)

# Check results
print("Items matched:", len(selected_items))

print("\nMissing item matches:")
print(selected_items["price"].isnull().sum())

print("\nSample:")
print(selected_items.head(10))

Items matched: 30000

Missing item matches:
0

Sample:
  item_id restaurant_id       cuisine             item_name     category  \
0   I0617          R080      Desserts        Chocolate Cake      Dessert
1   I0438          R056         Pizza    Cheese Burst Pizza  Main Course
2   I1155          R149       Biryani            Chicken 65      Starter
3   I0353          R045  South Indian           Vada Sambar  Main Course
4   I0607          R079          Cafe           Cold Coffee     Beverage
5   I0770          R100  North Indian           Dal Makhani  Main Course
6   I0944          R123       Healthy        Veg Salad Bowl      Healthy
7   I0522          R067       Healthy             Oats Bowl    Breakfast
8   I0802          R104       Healthy  Grilled Chicken Bowl      Healthy
9   I0429          R055       Biryani            Chicken 65      Starter

   price veg_flag  prep_time_min  popularity_score
0    150      Veg             12                33
1    398      Veg             20                63
2    211  Non-Veg             18                91
3    101      Veg             10                84
4    136      Veg              7                84
5    176      Veg             18                67
6    191      Veg             10                61
7    135      Veg             10                89
8    274  Non-Veg             18                66
9    234  Non-Veg             18                81

In [99]:
# ============================================
# STEP 4.8.10B: Calculate Order Value
# ============================================

np.random.seed(42)

# --------------------------------------------
# Get discount percentage for each restaurant
# --------------------------------------------

restaurant_discount_lookup = restaurants[
    ["restaurant_id", "discount_pct"]
].copy()

selected_items = selected_items.merge(
    restaurant_discount_lookup,
    on="restaurant_id",
    how="left"
)

# Check for missing discounts
print("Missing restaurant discounts:")
print(selected_items["discount_pct"].isnull().sum())


# --------------------------------------------
# Calculate discount amount
# --------------------------------------------

selected_items["discount_amount"] = (
    selected_items["price"]
    * selected_items["discount_pct"]
    / 100
)


# --------------------------------------------
# Calculate discounted food amount
# --------------------------------------------

selected_items["food_amount"] = (
    selected_items["price"]
    - selected_items["discount_amount"]
)


# --------------------------------------------
# Generate delivery/platform fee
# --------------------------------------------

delivery_fees = np.random.choice(
    [20, 25, 30, 35, 40],
    size=n_orders,
    p=[0.15, 0.25, 0.30, 0.20, 0.10]
)

selected_items["delivery_fee"] = delivery_fees


# --------------------------------------------
# Final amount paid by customer
# --------------------------------------------

selected_items["order_value"] = (
    selected_items["food_amount"]
    + selected_items["delivery_fee"]
)


# --------------------------------------------
# Check results
# --------------------------------------------

print("\nOrder value summary:")
print(
    selected_items[
        [
            "price",
            "discount_pct",
            "discount_amount",
            "food_amount",
            "delivery_fee",
            "order_value"
        ]
    ].describe()
)

print("\nSample:")
print(
    selected_items[
        [
            "item_id",
            "item_name",
            "price",
            "discount_pct",
            "discount_amount",
            "delivery_fee",
            "order_value"
        ]
    ].head(10)
)

Missing restaurant discounts:
0

Order value summary:
              price  discount_pct  discount_amount   food_amount  \
count  30000.000000  30000.000000     30000.000000  30000.000000
mean     186.418400     20.066500        36.270710    150.147690
std       75.532664     11.847057        26.462358     69.408457
min       54.000000      0.000000         0.000000     34.800000
25%      135.000000     10.000000        16.500000    100.800000
50%      174.000000     20.000000        30.500000    137.750000
75%      220.000000     30.000000        51.400000    179.400000
max      436.000000     40.000000       124.000000    417.000000

       delivery_fee   order_value
count  30000.000000  30000.000000
mean      29.235000    179.382690
std        5.957709     69.027786
min       20.000000     67.000000
25%       25.000000    133.250000
50%       30.000000    167.600000
75%       35.000000    207.400000
max       40.000000    454.000000

Sample:
  item_id             item_name  price  discount_pct  discount_amount  \
0   I0617        Chocolate Cake    150             5             7.50
1   I0438    Cheese Burst Pizza    398            25            99.50
2   I1155            Chicken 65    211            20            42.20
3   I0353           Vada Sambar    101            15            15.15
4   I0607           Cold Coffee    136            30            40.80
5   I0770           Dal Makhani    176            25            44.00
6   I0944        Veg Salad Bowl    191            10            19.10
7   I0522             Oats Bowl    135            40            54.00
8   I0802  Grilled Chicken Bowl    274             0             0.00
9   I0429            Chicken 65    234             5            11.70

   delivery_fee  order_value
0            25       167.50
1            40       338.50
2            35       203.80
3            30       115.85
4            25       120.20
5            25       157.00
6            20       191.90
7            35       116.00
8            30       304.00
9            35       257.30

In [100]:
# ============================================
# STEP 4.8.11: Assign Order Status
# ============================================

# Use a separate random generator
rng_status = np.random.default_rng(2025)

order_status = []

for platform in order_platforms:

    if platform == "Swiggy":

        status = rng_status.choice(
            ["Delivered", "Cancelled", "Failed"],
            p=[0.94, 0.04, 0.02]
        )

    elif platform == "Zomato":

        status = rng_status.choice(
            ["Delivered", "Cancelled", "Failed"],
            p=[0.94, 0.04, 0.02]
        )

    else:  # Direct

        status = rng_status.choice(
            ["Delivered", "Cancelled", "Failed"],
            p=[0.70, 0.20, 0.10]
        )

    order_status.append(status)


order_status = np.array(order_status)


# --------------------------------------------
# Check results
# --------------------------------------------

print("Order statuses assigned:", len(order_status))

print("\nOrder status distribution:")
print(
    pd.Series(order_status)
    .value_counts()
)

print("\nOrder status percentage:")
print(
    pd.Series(order_status)
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

Order statuses assigned: 30000

Order status distribution:
Delivered    27583
Cancelled     1624
Failed         793
Name: count, dtype: int64

Order status percentage:
Delivered    91.94
Cancelled     5.41
Failed        2.64
Name: proportion, dtype: float64

In [101]:
# ============================================
# STEP 4.8.12: Assign Customer Ratings
# ============================================

np.random.seed(42)

# Start with all ratings as missing
order_ratings = np.full(
    n_orders,
    np.nan
)

# Get restaurant ratings for each order
order_restaurant_ratings = restaurants.set_index(
    "restaurant_id"
).loc[
    order_restaurant_ids,
    "rating"
].values

# Identify delivered orders
delivered_mask = (
    np.array(order_status) == "Delivered"
)

# Generate ratings only for delivered orders
base_ratings = (
    order_restaurant_ratings[delivered_mask]
    + np.random.normal(
        loc=0,
        scale=0.6,
        size=delivered_mask.sum()
    )
)

# Round to nearest whole number
generated_ratings = np.round(
    base_ratings
)

# Keep ratings between 1 and 5
generated_ratings = np.clip(
    generated_ratings,
    1,
    5
)

# Assign ratings
order_ratings[delivered_mask] = generated_ratings

# Check results
print("Ratings generated:", delivered_mask.sum())

print("\nMissing ratings:")
print(
    np.isnan(order_ratings).sum()
)

print("\nRating distribution:")
print(
    pd.Series(order_ratings)
    .value_counts(dropna=False)
    .sort_index()
)

Ratings generated: 27583

Missing ratings:
2417

Rating distribution:
1.0       18
2.0      793
3.0     6628
4.0    12353
5.0     7791
NaN     2417
Name: count, dtype: int64

In [102]:
# ============================================
# STEP 4.9: Create Master Orders Table
# ============================================

orders = pd.DataFrame({

    # Unique order ID
    "order_id": [
        f"O{i:06d}"
        for i in range(1, n_orders + 1)
    ],

    # Customer information
    "customer_id": order_customer_ids,

    # Customer locality
    "locality_id": order_localities,

    # Customer segment
    "customer_segment": order_segments,

    # Preferred cuisine
    "preferred_cuisine": order_preferred_cuisines,

    # Date and time
    "order_date": pd.to_datetime(order_dates),

    "order_time": order_times,

    # Restaurant
    "restaurant_id": order_restaurant_ids,

    # Menu item
    "item_id": order_item_ids,

    # Platform
    "platform": order_platforms,

    # Order status
    "order_status": order_status,

    # Rating
    "customer_rating": order_ratings,

    # Financial information
    "item_price": selected_items["price"].values,

    "discount_pct": selected_items["discount_pct"].values,

    "discount_amount": selected_items["discount_amount"].values,

    "food_amount": selected_items["food_amount"].values,

    "delivery_fee": selected_items["delivery_fee"].values,

    "order_value": selected_items["order_value"].values
})


# --------------------------------------------
# Check the table
# --------------------------------------------

print("Number of orders:", len(orders))

print("Number of columns:", len(orders.columns))

print("\nColumns:")
print(orders.columns.tolist())

print("\nFirst 10 orders:")
print(orders.head(10))

Number of orders: 30000
Number of columns: 18

Columns:
['order_id', 'customer_id', 'locality_id', 'customer_segment', 'preferred_cuisine', 'order_date', 'order_time', 'restaurant_id', 'item_id', 'platform', 'order_status', 'customer_rating', 'item_price', 'discount_pct', 'discount_amount', 'food_amount', 'delivery_fee', 'order_value']

First 10 orders:
  order_id customer_id  locality_id    customer_segment preferred_cuisine  \
0  O000001      C01847            9              Family             Momos
1  O000002      C04755            4             Student             Pizza
2  O000003      C03641            4             Student           Biryani
3  O000004      C02965           10  Young Professional             Pizza
4  O000005      C00768            6  Young Professional             Pizza
5  O000006      C00768            6  Young Professional             Pizza
6  O000007      C00280            7  Young Professional              Cafe
7  O000008      C04328            8             Student             Momos
8  O000009      C02977            6  Young Professional           Biryani
9  O000010      C03511           10  Young Professional           Biryani

  order_date order_time restaurant_id item_id platform order_status  \
0 2025-05-17   14:12:00          R080   I0617   Swiggy       Failed
1 2025-12-13   23:26:00          R056   I0438   Swiggy    Delivered
2 2025-09-25   20:37:00          R149   I1155   Direct    Cancelled
3 2025-08-07   19:32:00          R045   I0353   Zomato    Delivered
4 2025-02-27   11:05:00          R079   I0607   Swiggy    Cancelled
5 2025-02-27   11:12:00          R100   I0770   Swiggy    Delivered
6 2025-01-22   08:12:00          R123   I0944   Swiggy    Delivered
7 2025-11-13   22:12:00          R067   I0522   Zomato    Delivered
8 2025-08-08   19:19:00          R104   I0802   Swiggy    Delivered
9 2025-09-16   20:35:00          R055   I0429   Zomato    Delivered

   customer_rating  item_price  discount_pct  discount_amount  food_amount  \
0              NaN         150             5             7.50       142.50
1              5.0         398            25            99.50       298.50
2              NaN         211            20            42.20       168.80
3              5.0         101            15            15.15        85.85
4              NaN         136            30            40.80        95.20
5              5.0         176            25            44.00       132.00
6              5.0         191            10            19.10       171.90
7              4.0         135            40            54.00        81.00
8              3.0         274             0             0.00       274.00
9              5.0         234             5            11.70       222.30

   delivery_fee  order_value
0            25       167.50
1            40       338.50
2            35       203.80
3            30       115.85
4            25       120.20
5            25       157.00
6            20       191.90
7            35       116.00
8            30       304.00
9            35       257.30

In [103]:
# ============================================
# STEP 4.10: DATA QUALITY AUDIT
# ============================================

print("=" * 60)
print("DATA QUALITY AUDIT")
print("=" * 60)


# 1. Check duplicate Order IDs
print("\n1. Duplicate Order IDs:")
print(orders["order_id"].duplicated().sum())


# 2. Check missing values
print("\n2. Missing Values:")
print(orders.isnull().sum())


# 3. Check invalid Customer IDs
invalid_customers = ~orders["customer_id"].isin(
    customers["customer_id"]
)

print("\n3. Invalid Customer IDs:")
print(invalid_customers.sum())


# 4. Check invalid Restaurant IDs
invalid_restaurants = ~orders["restaurant_id"].isin(
    restaurants["restaurant_id"]
)

print("\n4. Invalid Restaurant IDs:")
print(invalid_restaurants.sum())


# 5. Check invalid Item IDs
invalid_items = ~orders["item_id"].isin(
    menu_items["item_id"]
)

print("\n5. Invalid Item IDs:")
print(invalid_items.sum())


# 6. Check date range
print("\n6. Order Date Range:")
print("Minimum:", orders["order_date"].min())
print("Maximum:", orders["order_date"].max())


# 7. Check invalid prices
invalid_prices = (
    orders["item_price"] <= 0
)

print("\n7. Invalid Prices:")
print(invalid_prices.sum())


# 8. Check invalid discounts
invalid_discounts = (
    (orders["discount_pct"] < 0) |
    (orders["discount_pct"] > 100)
)

print("\n8. Invalid Discounts:")
print(invalid_discounts.sum())


# 9. Check invalid ratings
invalid_ratings = (
    orders["customer_rating"].notna() &
    (
        (orders["customer_rating"] < 1) |
        (orders["customer_rating"] > 5)
    )
)

print("\n9. Invalid Ratings:")
print(invalid_ratings.sum())


# 10. Check rating/status consistency
invalid_rating_status = (
    (
        orders["order_status"] != "Delivered"
    ) &
    orders["customer_rating"].notna()
)

print("\n10. Non-delivered orders with ratings:")
print(invalid_rating_status.sum())


# 11. Check delivered orders without ratings
missing_delivered_rating = (
    (
        orders["order_status"] == "Delivered"
    ) &
    orders["customer_rating"].isna()
)

print("\n11. Delivered orders without ratings:")
print(missing_delivered_rating.sum())


# 12. Check financial calculation
calculated_order_value = (
    orders["food_amount"]
    + orders["delivery_fee"]
)

financial_errors = (
    abs(
        orders["order_value"]
        - calculated_order_value
    ) > 0.01
)

print("\n12. Financial calculation errors:")
print(financial_errors.sum())


# 13. Check number of rows
print("\n13. Number of rows:")
print(len(orders))


# 14. Check number of columns
print("\n14. Number of columns:")
print(len(orders.columns))


print("\n" + "=" * 60)
print("AUDIT COMPLETE")
print("=" * 60)

============================================================
DATA QUALITY AUDIT
============================================================

1. Duplicate Order IDs:
0

2. Missing Values:
order_id                0
customer_id             0
locality_id             0
customer_segment        0
preferred_cuisine       0
order_date              0
order_time              0
restaurant_id           0
item_id                 0
platform                0
order_status            0
customer_rating      2417
item_price              0
discount_pct            0
discount_amount         0
food_amount             0
delivery_fee            0
order_value             0
dtype: int64

3. Invalid Customer IDs:
0

4. Invalid Restaurant IDs:
0

5. Invalid Item IDs:
0

6. Order Date Range:
Minimum: 2025-01-01 00:00:00
Maximum: 2025-12-31 00:00:00

7. Invalid Prices:
0

8. Invalid Discounts:
0

9. Invalid Ratings:
0

10. Non-delivered orders with ratings:
0

11. Delivered orders without ratings:
0

12. Financial calculation errors:
0

13. Number of rows:
30000

14. Number of columns:
18

============================================================
AUDIT COMPLETE
============================================================

In [104]:
# ============================================
# STEP 4.11: CREATE ANALYTICAL DATE/TIME COLUMNS
# ============================================

# Make sure order_date is datetime
orders["order_date"] = pd.to_datetime(
    orders["order_date"]
)

# --------------------------------------------
# Date-related columns
# --------------------------------------------

orders["year"] = orders["order_date"].dt.year

orders["month"] = orders["order_date"].dt.month

orders["month_name"] = orders["order_date"].dt.strftime(
    "%B"
)

orders["day_of_week"] = orders["order_date"].dt.dayofweek

orders["day_name"] = orders["order_date"].dt.strftime(
    "%A"
)

# Weekend flag
orders["is_weekend"] = np.where(
    orders["day_of_week"] >= 5,
    "Yes",
    "No"
)


# --------------------------------------------
# Time-related columns
# --------------------------------------------

orders["order_hour"] = pd.to_datetime(
    orders["order_time"],
    format="%H:%M:%S"
).dt.hour


# --------------------------------------------
# Meal period
# --------------------------------------------

def get_meal_period(hour):

    if 7 <= hour <= 11:
        return "Breakfast"

    elif 12 <= hour <= 15:
        return "Lunch"

    elif 16 <= hour <= 18:
        return "Evening"

    elif 19 <= hour <= 23:
        return "Dinner"

    else:
        return "Late Night"


orders["meal_period"] = orders["order_hour"].apply(
    get_meal_period
)


# --------------------------------------------
# Check results
# --------------------------------------------

print("New columns created:")
print([
    "year",
    "month",
    "month_name",
    "day_of_week",
    "day_name",
    "is_weekend",
    "order_hour",
    "meal_period"
])

print("\nSample:")
print(
    orders[
        [
            "order_date",
            "order_time",
            "year",
            "month",
            "month_name",
            "day_name",
            "is_weekend",
            "order_hour",
            "meal_period"
        ]
    ].head(10)
)

New columns created:
['year', 'month', 'month_name', 'day_of_week', 'day_name', 'is_weekend', 'order_hour', 'meal_period']

Sample:
  order_date order_time  year  month month_name   day_name is_weekend  \
0 2025-05-17   14:12:00  2025      5        May   Saturday        Yes
1 2025-12-13   23:26:00  2025     12   December   Saturday        Yes
2 2025-09-25   20:37:00  2025      9  September   Thursday         No
3 2025-08-07   19:32:00  2025      8     August   Thursday         No
4 2025-02-27   11:05:00  2025      2   February   Thursday         No
5 2025-02-27   11:12:00  2025      2   February   Thursday         No
6 2025-01-22   08:12:00  2025      1    January  Wednesday         No
7 2025-11-13   22:12:00  2025     11   November   Thursday         No
8 2025-08-08   19:19:00  2025      8     August     Friday         No
9 2025-09-16   20:35:00  2025      9  September    Tuesday         No

   order_hour meal_period
0          14       Lunch
1          23      Dinner
2          20      Dinner
3          19      Dinner
4          11   Breakfast
5          11   Breakfast
6           8   Breakfast
7          22      Dinner
8          19      Dinner
9          20      Dinner

In [105]:
# ============================================
# STEP 4.12: BUSINESS VALIDATION
# ============================================

print("=" * 70)
print("BUSINESS VALIDATION")
print("=" * 70)


# --------------------------------------------
# 1. Orders by Hour
# --------------------------------------------

hourly_orders = (
    orders
    .groupby("order_hour")
    .size()
    .sort_values(ascending=False)
)

print("\n1. ORDERS BY HOUR")
print(hourly_orders)


# --------------------------------------------
# 2. Orders by Day
# --------------------------------------------

daily_orders = (
    orders
    .groupby(["day_of_week", "day_name"])
    .size()
    .sort_values(ascending=False)
)

print("\n2. ORDERS BY DAY")
print(daily_orders)


# --------------------------------------------
# 3. Orders by Cuisine
# --------------------------------------------

cuisine_orders = (
    orders
    .groupby("preferred_cuisine")
    .size()
    .sort_values(ascending=False)
)

print("\n3. ORDERS BY CUSTOMER PREFERRED CUISINE")
print(cuisine_orders)


# --------------------------------------------
# 4. Orders by Platform
# --------------------------------------------

platform_orders = (
    orders
    .groupby("platform")
    .size()
    .sort_values(ascending=False)
)

print("\n4. ORDERS BY PLATFORM")
print(platform_orders)


# --------------------------------------------
# 5. Orders by Customer Segment
# --------------------------------------------

segment_orders = (
    orders
    .groupby("customer_segment")
    .size()
    .sort_values(ascending=False)
)

print("\n5. ORDERS BY CUSTOMER SEGMENT")
print(segment_orders)


print("\n" + "=" * 70)
print("VALIDATION COMPLETE")
print("=" * 70)

======================================================================
BUSINESS VALIDATION
======================================================================

1. ORDERS BY HOUR
order_hour
21    3084
20    2953
13    2623
22    2610
14    2390
19    2367
12    2176
18    1552
23    1544
17    1292
9     1281
15    1260
11    1190
8     1088
10     924
16     895
7      771
dtype: int64

2. ORDERS BY DAY
day_of_week  day_name
5            Saturday     5377
6            Sunday       4989
4            Friday       4515
3            Thursday     3958
2            Wednesday    3944
1            Tuesday      3637
0            Monday       3580
dtype: int64

3. ORDERS BY CUSTOMER PREFERRED CUISINE
preferred_cuisine
Biryani         4746
Chinese         4686
Pizza           3981
North Indian    3837
Momos           2950
Burgers         2646
South Indian    2160
Cafe            2153
Healthy         1734
Desserts        1107
dtype: int64

4. ORDERS BY PLATFORM
platform
Zomato    13517
Swiggy    13493
Direct     2990
dtype: int64

5. ORDERS BY CUSTOMER SEGMENT
customer_segment
Student                 9021
Working Professional    8705
Family                  6248
Young Professional      6026
dtype: int64

======================================================================
VALIDATION COMPLETE
======================================================================

In [106]:
# ============================================
# STEP 4.13: ADD ACTUAL ITEM DETAILS TO ORDERS
# ============================================

# Create item details lookup
item_details = menu_items[
    [
        "item_id",
        "item_name",
        "cuisine",
        "category",
        "veg_flag"
    ]
].copy()

# Rename cuisine so we don't confuse it
# with customer's preferred cuisine
item_details = item_details.rename(
    columns={
        "cuisine": "ordered_cuisine"
    }
)

# Merge actual item information
orders = orders.merge(
    item_details,
    on="item_id",
    how="left"
)

# --------------------------------------------
# Validate
# --------------------------------------------

print("Orders after merge:", len(orders))

print("\nMissing item names:")
print(orders["item_name"].isnull().sum())

print("\nMissing ordered cuisines:")
print(orders["ordered_cuisine"].isnull().sum())

print("\nSample:")
print(
    orders[
        [
            "order_id",
            "customer_id",
            "preferred_cuisine",
            "item_id",
            "item_name",
            "ordered_cuisine",
            "category",
            "veg_flag"
        ]
    ].head(10)
)

Orders after merge: 30000

Missing item names:
0

Missing ordered cuisines:
0

Sample:
  order_id customer_id preferred_cuisine item_id             item_name  \
0  O000001      C01847             Momos   I0617        Chocolate Cake
1  O000002      C04755             Pizza   I0438    Cheese Burst Pizza
2  O000003      C03641           Biryani   I1155            Chicken 65
3  O000004      C02965             Pizza   I0353           Vada Sambar
4  O000005      C00768             Pizza   I0607           Cold Coffee
5  O000006      C00768             Pizza   I0770           Dal Makhani
6  O000007      C00280              Cafe   I0944        Veg Salad Bowl
7  O000008      C04328             Momos   I0522             Oats Bowl
8  O000009      C02977           Biryani   I0802  Grilled Chicken Bowl
9  O000010      C03511           Biryani   I0429            Chicken 65

  ordered_cuisine     category veg_flag
0        Desserts      Dessert      Veg
1           Pizza  Main Course      Veg
2         Biryani      Starter  Non-Veg
3    South Indian  Main Course      Veg
4            Cafe     Beverage      Veg
5    North Indian  Main Course      Veg
6         Healthy      Healthy      Veg
7         Healthy    Breakfast      Veg
8         Healthy      Healthy  Non-Veg
9         Biryani      Starter  Non-Veg

In [107]:
# ============================================
# STEP 4.14: ACTUAL CUISINE SALES ANALYSIS
# ============================================

# Count orders by actual ordered cuisine
cuisine_sales = (
    orders
    .groupby("ordered_cuisine")
    .agg(
        total_orders=("order_id", "count"),
        total_revenue=("order_value", "sum"),
        average_order_value=("order_value", "mean")
    )
    .sort_values(
        "total_orders",
        ascending=False
    )
)

# Round revenue and AOV
cuisine_sales["total_revenue"] = (
    cuisine_sales["total_revenue"]
    .round(2)
)

cuisine_sales["average_order_value"] = (
    cuisine_sales["average_order_value"]
    .round(2)
)

print("ACTUAL CUISINE SALES")
print("=" * 60)
print(cuisine_sales)

print("\n\nBEST-SELLING CUISINE:")
print(
    cuisine_sales.index[0],
    "→",
    cuisine_sales.iloc[0]["total_orders"],
    "orders"
)

print("\nHIGHEST REVENUE CUISINE:")
print(
    cuisine_sales["total_revenue"]
    .idxmax(),
    "→ ₹",
    cuisine_sales["total_revenue"].max()
)

ACTUAL CUISINE SALES
============================================================
                 total_orders  total_revenue  average_order_value
ordered_cuisine
North Indian             5403      932745.00               172.63
South Indian             3691      425664.25               115.32
Biryani                  3661      694912.50               189.81
Pizza                    3619     1059515.60               292.76
Chinese                  3256      531739.40               163.31
Healthy                  2875      546173.85               189.97
Burgers                  2114      372244.55               176.09
Desserts                 2041      312286.55               153.01
Momos                    1997      322190.15               161.34
Cafe                     1343      184008.85               137.01


BEST-SELLING CUISINE:
North Indian → 5403.0 orders

HIGHEST REVENUE CUISINE:
Pizza → ₹ 1059515.6

In [108]:
# ============================================
# STEP 4.15: BEST-SELLING MENU ITEMS
# ============================================

item_sales = (
    orders
    .groupby(
        [
            "item_id",
            "item_name",
            "ordered_cuisine",
            "category"
        ]
    )
    .agg(
        total_orders=("order_id", "count"),
        total_revenue=("order_value", "sum"),
        average_order_value=("order_value", "mean"),
        average_rating=("customer_rating", "mean")
    )
    .sort_values(
        "total_orders",
        ascending=False
    )
)

item_sales["total_revenue"] = (
    item_sales["total_revenue"].round(2)
)

item_sales["average_order_value"] = (
    item_sales["average_order_value"].round(2)
)

item_sales["average_rating"] = (
    item_sales["average_rating"].round(2)
)

print("TOP 20 BEST-SELLING ITEMS")
print("=" * 80)

print(item_sales.head(20))

TOP 20 BEST-SELLING ITEMS
================================================================================
                                                           total_orders  \
item_id item_name             ordered_cuisine category
I0432   Margherita Pizza      Pizza           Main Course           147
I0436   Pepperoni Pizza       Pizza           Main Course           125
I0518   Paneer Bowl           Healthy         Healthy               113
I0569   Veg Hakka Noodles     Chinese         Main Course           104
I0742   Protein Smoothie      Healthy         Beverage              103
I0328   Paneer Momos          Momos           Main Course            93
I0575   Manchurian            Chinese         Starter                92
I0867   Masala Dosa           South Indian    Main Course            91
I0852   Chicken Hakka Noodles Chinese         Main Course            89
I0738   Chicken Salad Bowl    Healthy         Healthy                88
I0191   Chicken Salad Bowl    Healthy         Healthy                88
I0574   Chilli Chicken        Chinese         Starter                87
I0438   Cheese Burst Pizza    Pizza           Main Course            85
I1058   Spring Rolls          Chinese         Starter                85
I0293   Cheese Burger         Burgers         Main Course            85
I0186   Paneer Tikka          North Indian    Starter                84
I0872   Uttapam               South Indian    Main Course            82
I0435   Chicken Pizza         Pizza           Main Course            82
I0740   Grilled Chicken Bowl  Healthy         Healthy                82
I1056   Chilli Chicken        Chinese         Starter                82

                                                           total_revenue  \
item_id item_name             ordered_cuisine category
I0432   Margherita Pizza      Pizza           Main Course       25791.25
I0436   Pepperoni Pizza       Pizza           Main Course       38453.75
I0518   Paneer Bowl           Healthy         Healthy           16525.60
I0569   Veg Hakka Noodles     Chinese         Main Course       18302.20
I0742   Protein Smoothie      Healthy         Beverage          19172.25
I0328   Paneer Momos          Momos           Main Course       14885.00
I0575   Manchurian            Chinese         Starter           16592.20
I0867   Masala Dosa           South Indian    Main Course        9808.80
I0852   Chicken Hakka Noodles Chinese         Main Course       15352.20
I0738   Chicken Salad Bowl    Healthy         Healthy           18200.00
I0191   Chicken Salad Bowl    Healthy         Healthy           15752.00
I0574   Chilli Chicken        Chinese         Starter           17436.05
I0438   Cheese Burst Pizza    Pizza           Main Course       28632.50
I1058   Spring Rolls          Chinese         Starter            9804.00
I0293   Cheese Burger         Burgers         Main Course       15285.50
I0186   Paneer Tikka          North Indian    Starter           12100.20
I0872   Uttapam               South Indian    Main Course        9418.40
I0435   Chicken Pizza         Pizza           Main Course       24124.50
I0740   Grilled Chicken Bowl  Healthy         Healthy           18805.50
I1056   Chilli Chicken        Chinese         Starter           13726.80

                                                           average_order_value  \
item_id item_name             ordered_cuisine category
I0432   Margherita Pizza      Pizza           Main Course               175.45
I0436   Pepperoni Pizza       Pizza           Main Course               307.63
I0518   Paneer Bowl           Healthy         Healthy                   146.24
I0569   Veg Hakka Noodles     Chinese         Main Course               175.98
I0742   Protein Smoothie      Healthy         Beverage                  186.14
I0328   Paneer Momos          Momos           Main Course               160.05
I0575   Manchurian            Chinese         Starter                   180.35
I0867   Masala Dosa           South Indian    Main Course               107.79
I0852   Chicken Hakka Noodles Chinese         Main Course               172.50
I0738   Chicken Salad Bowl    Healthy         Healthy                   206.82
I0191   Chicken Salad Bowl    Healthy         Healthy                   179.00
I0574   Chilli Chicken        Chinese         Starter                   200.41
I0438   Cheese Burst Pizza    Pizza           Main Course               336.85
I1058   Spring Rolls          Chinese         Starter                   115.34
I0293   Cheese Burger         Burgers         Main Course               179.83
I0186   Paneer Tikka          North Indian    Starter                   144.05
I0872   Uttapam               South Indian    Main Course               114.86
I0435   Chicken Pizza         Pizza           Main Course               294.20
I0740   Grilled Chicken Bowl  Healthy         Healthy                   229.34
I1056   Chilli Chicken        Chinese         Starter                   167.40

                                                           average_rating
item_id item_name             ordered_cuisine category
I0432   Margherita Pizza      Pizza           Main Course            4.54
I0436   Pepperoni Pizza       Pizza           Main Course            4.52
I0518   Paneer Bowl           Healthy         Healthy                4.33
I0569   Veg Hakka Noodles     Chinese         Main Course            4.54
I0742   Protein Smoothie      Healthy         Beverage               4.45
I0328   Paneer Momos          Momos           Main Course            3.62
I0575   Manchurian            Chinese         Starter                4.61
I0867   Masala Dosa           South Indian    Main Course            4.57
I0852   Chicken Hakka Noodles Chinese         Main Course            4.68
I0738   Chicken Salad Bowl    Healthy         Healthy                4.49
I0191   Chicken Salad Bowl    Healthy         Healthy                4.11
I0574   Chilli Chicken        Chinese         Starter                4.64
I0438   Cheese Burst Pizza    Pizza           Main Course            4.54
I1058   Spring Rolls          Chinese         Starter                4.21
I0293   Cheese Burger         Burgers         Main Course            4.57
I0186   Paneer Tikka          North Indian    Starter                4.35
I0872   Uttapam               South Indian    Main Course            4.54
I0435   Chicken Pizza         Pizza           Main Course            4.54
I0740   Grilled Chicken Bowl  Healthy         Healthy                4.55
I1056   Chilli Chicken        Chinese         Starter                4.34

In [109]:
# ============================================
# STEP 4.16: LOCALITY-LEVEL ANALYSIS
# ============================================

locality_analysis = (
    orders
    .groupby("locality_id")
    .agg(
        total_orders=("order_id", "count"),

        total_revenue=("order_value", "sum"),

        average_order_value=("order_value", "mean"),

        delivered_orders=(
            "order_status",
            lambda x: (x == "Delivered").sum()
        ),

        cancelled_orders=(
            "order_status",
            lambda x: (x == "Cancelled").sum()
        ),

        failed_orders=(
            "order_status",
            lambda x: (x == "Failed").sum()
        ),

        average_rating=("customer_rating", "mean")
    )
)

# --------------------------------------------
# Calculate cancellation rate
# --------------------------------------------

locality_analysis["cancellation_rate"] = (
    locality_analysis["cancelled_orders"]
    / locality_analysis["total_orders"]
    * 100
)

# --------------------------------------------
# Calculate failure rate
# --------------------------------------------

locality_analysis["failure_rate"] = (
    locality_analysis["failed_orders"]
    / locality_analysis["total_orders"]
    * 100
)

# --------------------------------------------
# Round values
# --------------------------------------------

locality_analysis["total_revenue"] = (
    locality_analysis["total_revenue"].round(2)
)

locality_analysis["average_order_value"] = (
    locality_analysis["average_order_value"].round(2)
)

locality_analysis["average_rating"] = (
    locality_analysis["average_rating"].round(2)
)

locality_analysis["cancellation_rate"] = (
    locality_analysis["cancellation_rate"].round(2)
)

locality_analysis["failure_rate"] = (
    locality_analysis["failure_rate"].round(2)
)


# --------------------------------------------
# Sort by demand
# --------------------------------------------

locality_analysis = locality_analysis.sort_values(
    "total_orders",
    ascending=False
)

print("LOCALITY-LEVEL ANALYSIS")
print("=" * 100)

print(locality_analysis)

LOCALITY-LEVEL ANALYSIS
====================================================================================================
             total_orders  total_revenue  average_order_value  \
locality_id
5                    3174      588352.45               185.37
1                    3120      549300.50               176.06
4                    3059      543067.85               177.53
3                    3055      565500.65               185.11
6                    3041      546882.05               179.84
8                    2999      529624.45               176.60
10                   2958      537942.90               181.86
9                    2925      516652.80               176.63
7                    2852      515011.40               180.58
2                    2817      489145.65               173.64

             delivered_orders  cancelled_orders  failed_orders  \
locality_id
5                        2958               134             82
1                        2879               156             85
4                        2817               154             88
3                        2789               184             82
6                        2793               166             82
8                        2745               164             90
10                       2724               170             64
9                        2676               172             77
7                        2632               156             64
2                        2570               168             79

             average_rating  cancellation_rate  failure_rate
locality_id
5                      4.03               4.22          2.58
1                      4.07               5.00          2.72
4                      3.92               5.03          2.88
3                      3.94               6.02          2.68
6                      4.01               5.46          2.70
8                      3.95               5.47          3.00
10                     3.93               5.75          2.16
9                      4.06               5.88          2.63
7                      3.93               5.47          2.24
2                      3.97               5.96          2.80

In [110]:
# ============================================
# STEP 4.17: LOCALITY × CUISINE ANALYSIS
# ============================================

locality_cuisine = (
    orders
    .groupby(
        [
            "locality_id",
            "ordered_cuisine"
        ]
    )
    .agg(
        total_orders=("order_id", "count"),
        total_revenue=("order_value", "sum"),
        average_order_value=("order_value", "mean"),
        average_rating=("customer_rating", "mean")
    )
    .reset_index()
)

# Round values
locality_cuisine["total_revenue"] = (
    locality_cuisine["total_revenue"].round(2)
)

locality_cuisine["average_order_value"] = (
    locality_cuisine["average_order_value"].round(2)
)

locality_cuisine["average_rating"] = (
    locality_cuisine["average_rating"].round(2)
)

# --------------------------------------------
# Find the #1 cuisine in each locality
# --------------------------------------------

top_cuisine_by_locality = (
    locality_cuisine
    .sort_values(
        ["locality_id", "total_orders"],
        ascending=[True, False]
    )
    .groupby("locality_id")
    .head(1)
)

print("TOP CUISINE IN EACH LOCALITY")
print("=" * 80)

print(
    top_cuisine_by_locality[
        [
            "locality_id",
            "ordered_cuisine",
            "total_orders",
            "total_revenue",
            "average_order_value",
            "average_rating"
        ]
    ].to_string(index=False)
)


# --------------------------------------------
# Full locality × cuisine table
# --------------------------------------------

print("\n\nFULL LOCALITY × CUISINE ANALYSIS")
print("=" * 80)

print(locality_cuisine.to_string(index=False))

TOP CUISINE IN EACH LOCALITY
================================================================================
 locality_id ordered_cuisine  total_orders  total_revenue  average_order_value  average_rating
           1    North Indian           736      123223.50               167.42            4.17
           2    South Indian           419       47649.50               113.72            4.18
           3    North Indian           488       90412.20               185.27            3.86
           4    North Indian           518       90251.25               174.23            3.87
           5    North Indian           502       86941.95               173.19            3.80
           6    North Indian           792      133231.45               168.22            4.11
           7         Biryani           491       90051.85               183.40            3.87
           8    North Indian           545       97665.10               179.20            3.97
           9    North Indian           568       97429.85               171.53            4.22
          10    North Indian           558       91787.35               164.49            3.94


FULL LOCALITY × CUISINE ANALYSIS
================================================================================
 locality_id ordered_cuisine  total_orders  total_revenue  average_order_value  average_rating
           1         Biryani           370       70993.05               191.87            3.69
           1         Burgers           165       29165.30               176.76            3.95
           1            Cafe           200       27078.40               135.39            4.35
           1         Chinese           380       61558.80               162.00            4.36
           1        Desserts           253       37127.35               146.75            3.90
           1         Healthy           266       49245.45               185.13            4.06
           1           Momos           151       24212.25               160.35            3.59
           1    North Indian           736      123223.50               167.42            4.17
           1           Pizza           341       97213.00               285.08            4.15
           1    South Indian           258       29483.40               114.28            4.09
           2         Biryani           263       50691.10               192.74            3.79
           2         Burgers           252       42906.00               170.26            3.82
           2            Cafe           203       26516.05               130.62            4.20
           2         Chinese           330       54965.60               166.56            4.06
           2        Desserts           178       27005.80               151.72            3.89
           2         Healthy           250       47989.20               191.96            3.84
           2           Momos           315       54014.20               171.47            3.75
           2    North Indian           339       58529.90               172.65            4.01
           2           Pizza           268       78878.30               294.32            4.10
           2    South Indian           419       47649.50               113.72            4.18
           3         Biryani           458       90164.30               196.87            3.59
           3         Burgers           265       48473.55               182.92            4.04
           3            Cafe            97       13420.20               138.35            3.89
           3         Chinese           431       70179.65               162.83            4.23
           3        Desserts           215       32515.25               151.23            4.04
           3         Healthy           224       42679.10               190.53            4.04
           3           Momos           166       26852.40               161.76            3.45
           3    North Indian           488       90412.20               185.27            3.86
           3           Pizza           360      110019.00               305.61            4.13
           3    South Indian           351       40785.00               116.20            3.99
           4         Biryani           390       68160.05               174.77            3.57
           4         Burgers           153       26805.35               175.20            4.00
           4            Cafe            95       13385.05               140.90            3.90
           4         Chinese           234       37843.90               161.73            4.15
           4        Desserts           186       28451.75               152.97            3.94
           4         Healthy           305       53313.20               174.80            4.03
           4           Momos           234       37752.35               161.33            3.66
           4    North Indian           518       90251.25               174.23            3.87
           4           Pizza           481      133395.55               277.33            4.13
           4    South Indian           463       53709.40               116.00            3.97
           5         Biryani           376       69673.35               185.30            3.87
           5         Burgers           233       41771.40               179.28            3.81
           5            Cafe            92       12944.75               140.70            3.94
           5         Chinese           473       80946.25               171.13            4.12
           5        Desserts           208       32932.65               158.33            4.08
           5         Healthy           293       57974.55               197.87            4.07
           5           Momos           113       18704.90               165.53            3.75
           5    North Indian           502       86941.95               173.19            3.80
           5           Pizza           448      138449.50               309.04            4.25
           5    South Indian           436       48013.15               110.12            4.29
           6         Biryani           399       79874.85               200.19            3.78
           6         Burgers           184       32711.15               177.78            3.97
           6            Cafe           125       18453.55               147.63            3.90
           6         Chinese           279       46033.90               165.00            4.06
           6        Desserts           238       36373.30               152.83            4.12
           6         Healthy           246       46532.75               189.16            3.95
           6           Momos           175       27508.70               157.19            3.69
           6    North Indian           792      133231.45               168.22            4.11
           6           Pizza           332       93927.80               282.92            4.14
           6    South Indian           271       32234.60               118.95            4.15
           7         Biryani           491       90051.85               183.40            3.87
           7         Burgers           134       22973.00               171.44            4.01
           7            Cafe           130       19280.50               148.31            3.53
           7         Chinese           336       54173.40               161.23            3.91
           7        Desserts           177       29174.40               164.83            4.21
           7         Healthy           262       51029.80               194.77            3.91
           7           Momos           197       31525.30               160.03            3.62
           7    North Indian           357       63272.45               177.23            4.06
           7           Pizza           352      104871.80               297.93            3.91
           7    South Indian           416       48658.90               116.97            4.06
           8         Biryani           353       66561.20               188.56            3.88
           8         Burgers           171       29915.20               174.94            3.94
           8            Cafe            99       13905.40               140.46            3.90
           8         Chinese           272       43842.15               161.18            4.06
           8        Desserts           238       35836.05               150.57            4.06
           8         Healthy           219       41377.10               188.94            4.03
           8           Momos           288       47105.25               163.56            3.65
           8    North Indian           545       97665.10               179.20            3.97
           8           Pizza           355      100220.65               282.31            3.89
           8    South Indian           459       53196.35               115.90            4.07
           9         Biryani           260       51170.70               196.81            3.79
           9         Burgers           330       57939.05               175.57            4.34
           9            Cafe            77       10550.45               137.02            4.11
           9         Chinese           306       47360.00               154.77            4.27
           9        Desserts           214       32495.00               151.85            4.18
           9         Healthy           334       62089.05               185.90            3.83
           9           Momos           212       31245.20               147.38            3.47
           9    North Indian           568       97429.85               171.53            4.22
           9           Pizza           321       91542.20               285.18            4.06
           9    South Indian           303       34831.30               114.95            4.06
          10         Biryani           301       57572.05               191.27            3.64
          10         Burgers           227       39584.55               174.38            3.82
          10            Cafe           225       28474.50               126.55            3.70
          10         Chinese           215       34835.75               162.03            4.07
          10        Desserts           134       20375.00               152.05            4.14
          10         Healthy           476       93943.65               197.36            3.98
          10           Momos           146       23269.60               159.38            3.63
          10    North Indian           558       91787.35               164.49            3.94
          10           Pizza           361      110997.80               307.47            3.93
          10    South Indian           315       37102.65               117.79            4.27

In [111]:
# ============================================
# STEP 4.18: PLATFORM PERFORMANCE ANALYSIS
# ============================================

platform_analysis = (
    orders
    .groupby("platform")
    .agg(
        total_orders=("order_id", "count"),

        total_revenue=("order_value", "sum"),

        average_order_value=("order_value", "mean"),

        delivered_orders=(
            "order_status",
            lambda x: (x == "Delivered").sum()
        ),

        cancelled_orders=(
            "order_status",
            lambda x: (x == "Cancelled").sum()
        ),

        failed_orders=(
            "order_status",
            lambda x: (x == "Failed").sum()
        ),

        average_rating=("customer_rating", "mean")
    )
)

# Calculate rates

platform_analysis["cancellation_rate"] = (
    platform_analysis["cancelled_orders"]
    / platform_analysis["total_orders"]
    * 100
)

platform_analysis["failure_rate"] = (
    platform_analysis["failed_orders"]
    / platform_analysis["total_orders"]
    * 100
)

platform_analysis["delivery_success_rate"] = (
    platform_analysis["delivered_orders"]
    / platform_analysis["total_orders"]
    * 100
)

# Round values

platform_analysis["total_revenue"] = (
    platform_analysis["total_revenue"].round(2)
)

platform_analysis["average_order_value"] = (
    platform_analysis["average_order_value"].round(2)
)

platform_analysis["average_rating"] = (
    platform_analysis["average_rating"].round(2)
)

platform_analysis["cancellation_rate"] = (
    platform_analysis["cancellation_rate"].round(2)
)

platform_analysis["failure_rate"] = (
    platform_analysis["failure_rate"].round(2)
)

platform_analysis["delivery_success_rate"] = (
    platform_analysis["delivery_success_rate"].round(2)
)

# Sort by orders

platform_analysis = platform_analysis.sort_values(
    "total_orders",
    ascending=False
)

print("PLATFORM PERFORMANCE")
print("=" * 100)

print(platform_analysis)

PLATFORM PERFORMANCE
====================================================================================================
          total_orders  total_revenue  average_order_value  delivered_orders  \
platform
Zomato           13517      2391060.9               176.89             12750
Swiggy           13493      2467885.6               182.90             12689
Direct            2990       522534.2               174.76              2144

          cancelled_orders  failed_orders  average_rating  cancellation_rate  \
platform
Zomato                 531            236            3.93               3.93
Swiggy                 531            273            4.03               3.94
Direct                 562            284            4.02              18.80

          failure_rate  delivery_success_rate
platform
Zomato            1.75                  94.33
Swiggy            2.02                  94.04
Direct            9.50                  71.71

In [112]:
# ============================================
# STEP 4.19: PLATFORM × ORDER STATUS
# ============================================

platform_status = pd.crosstab(
    orders["platform"],
    orders["order_status"]
)

print("PLATFORM × ORDER STATUS")
print("=" * 70)

print(platform_status)


# --------------------------------------------
# Percentage within each platform
# --------------------------------------------

platform_status_pct = pd.crosstab(
    orders["platform"],
    orders["order_status"],
    normalize="index"
) * 100

platform_status_pct = platform_status_pct.round(2)

print("\n\nPLATFORM × ORDER STATUS (%)")
print("=" * 70)

print(platform_status_pct)

PLATFORM × ORDER STATUS
======================================================================
order_status  Cancelled  Delivered  Failed
platform
Direct              562       2144     284
Swiggy              531      12689     273
Zomato              531      12750     236


PLATFORM × ORDER STATUS (%)
======================================================================
order_status  Cancelled  Delivered  Failed
platform
Direct            18.80      71.71    9.50
Swiggy             3.94      94.04    2.02
Zomato             3.93      94.33    1.75

In [113]:
# ============================================
# STEP 4.20: CUSTOMER SEGMENT PERFORMANCE
# ============================================

segment_performance = orders.groupby("customer_segment").agg(

    # Total number of orders
    total_orders=("order_id", "count"),

    # Total revenue
    total_revenue=("order_value", "sum"),

    # Average order value
    average_order_value=("order_value", "mean"),

    # Number of delivered orders
    delivered_orders=("order_status", lambda x: (x == "Delivered").sum()),

    # Number of cancelled orders
    cancelled_orders=("order_status", lambda x: (x == "Cancelled").sum()),

    # Number of failed orders
    failed_orders=("order_status", lambda x: (x == "Failed").sum()),

    # Average customer rating
    average_rating=("customer_rating", "mean")
)


# --------------------------------------------
# Calculate cancellation rate
# --------------------------------------------

segment_performance["cancellation_rate"] = (
    segment_performance["cancelled_orders"]
    / segment_performance["total_orders"]
    * 100
)


# --------------------------------------------
# Calculate failure rate
# --------------------------------------------

segment_performance["failure_rate"] = (
    segment_performance["failed_orders"]
    / segment_performance["total_orders"]
    * 100
)


# --------------------------------------------
# Round the values
# --------------------------------------------

segment_performance = segment_performance.round({
    "total_revenue": 2,
    "average_order_value": 2,
    "average_rating": 2,
    "cancellation_rate": 2,
    "failure_rate": 2
})


# --------------------------------------------
# Display results
# --------------------------------------------

print("CUSTOMER SEGMENT PERFORMANCE")
print("=" * 100)

print(segment_performance)

CUSTOMER SEGMENT PERFORMANCE
====================================================================================================
                      total_orders  total_revenue  average_order_value  \
customer_segment
Family                        6248     1116768.20               178.74
Student                       9021     1629448.85               180.63
Working Professional          8705     1551639.25               178.25
Young Professional            6026     1083624.40               179.82

                      delivered_orders  cancelled_orders  failed_orders  \
customer_segment
Family                            5759               322            167
Student                           8294               491            236
Working Professional              7961               510            234
Young Professional                5569               301            156

                      average_rating  cancellation_rate  failure_rate
customer_segment
Family                          3.97               5.15          2.67
Student                         3.98               5.44          2.62
Working Professional            3.99               5.86          2.69
Young Professional              3.99               5.00          2.59

In [114]:
# ============================================
# STEP 4.21: MONTHLY PERFORMANCE
# ============================================

monthly_performance = orders.groupby(
    ["month", "month_name"]
).agg(

    # Total orders
    total_orders=("order_id", "count"),

    # Total revenue
    total_revenue=("order_value", "sum"),

    # Average order value
    average_order_value=("order_value", "mean"),

    # Delivered orders
    delivered_orders=(
        "order_status",
        lambda x: (x == "Delivered").sum()
    ),

    # Cancelled orders
    cancelled_orders=(
        "order_status",
        lambda x: (x == "Cancelled").sum()
    ),

    # Failed orders
    failed_orders=(
        "order_status",
        lambda x: (x == "Failed").sum()
    ),

    # Average rating
    average_rating=("customer_rating", "mean")
)


# --------------------------------------------
# Calculate cancellation rate
# --------------------------------------------

monthly_performance["cancellation_rate"] = (
    monthly_performance["cancelled_orders"]
    / monthly_performance["total_orders"]
    * 100
)


# --------------------------------------------
# Calculate failure rate
# --------------------------------------------

monthly_performance["failure_rate"] = (
    monthly_performance["failed_orders"]
    / monthly_performance["total_orders"]
    * 100
)


# --------------------------------------------
# Round values
# --------------------------------------------

monthly_performance = monthly_performance.round({
    "total_revenue": 2,
    "average_order_value": 2,
    "average_rating": 2,
    "cancellation_rate": 2,
    "failure_rate": 2
})


# --------------------------------------------
# Sort by month
# --------------------------------------------

monthly_performance = monthly_performance.sort_index(
    level="month"
)


# --------------------------------------------
# Display results
# --------------------------------------------

print("MONTHLY PERFORMANCE")
print("=" * 100)

print(monthly_performance)

MONTHLY PERFORMANCE
====================================================================================================
                  total_orders  total_revenue  average_order_value  \
month month_name
1     January             2571      430483.95               167.44
2     February            2245      398389.25               177.46
3     March               2570      480129.20               186.82
4     April               2418      429198.35               177.50
5     May                 2626      469492.95               178.79
6     June                2446      483080.65               197.50
7     July                2569      507796.75               197.66
8     August              2626      515076.25               196.14
9     September           2438      435393.00               178.59
10    October             2529      378267.55               149.57
11    November            2474      406621.25               164.36
12    December            2488      447551.55               179.88

                  delivered_orders  cancelled_orders  failed_orders  \
month month_name
1     January                 2358               157             56
2     February                2052               132             61
3     March                   2357               145             68
4     April                   2229               124             65
5     May                     2398               152             76
6     June                    2272               110             64
7     July                    2358               138             73
8     August                  2409               149             68
9     September               2269               106             63
10    October                 2317               145             67
11    November                2270               134             70
12    December                2294               132             62

                  average_rating  cancellation_rate  failure_rate
month month_name
1     January               3.99               6.11          2.18
2     February              3.98               5.88          2.72
3     March                 3.99               5.64          2.65
4     April                 3.97               5.13          2.69
5     May                   3.97               5.79          2.89
6     June                  3.99               4.50          2.62
7     July                  3.97               5.37          2.84
8     August                3.96               5.67          2.59
9     September             3.98               4.35          2.58
10    October               4.00               5.73          2.65
11    November              3.98               5.42          2.83
12    December              4.01               5.31          2.49

In [115]:
# ============================================
# STEP 4.22: WEEKEND vs WEEKDAY PERFORMANCE
# ============================================

weekend_performance = orders.groupby("is_weekend").agg(

    # Total orders
    total_orders=("order_id", "count"),

    # Total revenue
    total_revenue=("order_value", "sum"),

    # Average order value
    average_order_value=("order_value", "mean"),

    # Delivered orders
    delivered_orders=(
        "order_status",
        lambda x: (x == "Delivered").sum()
    ),

    # Cancelled orders
    cancelled_orders=(
        "order_status",
        lambda x: (x == "Cancelled").sum()
    ),

    # Failed orders
    failed_orders=(
        "order_status",
        lambda x: (x == "Failed").sum()
    ),

    # Average rating
    average_rating=("customer_rating", "mean")
)


# --------------------------------------------
# Calculate cancellation rate
# --------------------------------------------

weekend_performance["cancellation_rate"] = (
    weekend_performance["cancelled_orders"]
    / weekend_performance["total_orders"]
    * 100
)


# --------------------------------------------
# Calculate failure rate
# --------------------------------------------

weekend_performance["failure_rate"] = (
    weekend_performance["failed_orders"]
    / weekend_performance["total_orders"]
    * 100
)


# --------------------------------------------
# Round values
# --------------------------------------------

weekend_performance = weekend_performance.round({
    "total_revenue": 2,
    "average_order_value": 2,
    "average_rating": 2,
    "cancellation_rate": 2,
    "failure_rate": 2
})


# --------------------------------------------
# Display results
# --------------------------------------------

print("WEEKEND vs WEEKDAY PERFORMANCE")
print("=" * 100)

print(weekend_performance)

WEEKEND vs WEEKDAY PERFORMANCE
====================================================================================================
            total_orders  total_revenue  average_order_value  \
is_weekend
No                 19634      3525455.2               179.56
Yes                10366      1856025.5               179.05

            delivered_orders  cancelled_orders  failed_orders  average_rating  \
is_weekend
No                     18011              1111            512            3.98
Yes                     9572               513            281            3.98

            cancellation_rate  failure_rate
is_weekend
No                       5.66          2.61
Yes                      4.95          2.71

In [116]:
# ============================================
# STEP 4.23: MEAL PERIOD PERFORMANCE
# ============================================

meal_period_performance = orders.groupby("meal_period").agg(

    # Total orders
    total_orders=("order_id", "count"),

    # Total revenue
    total_revenue=("order_value", "sum"),

    # Average order value
    average_order_value=("order_value", "mean"),

    # Delivered orders
    delivered_orders=(
        "order_status",
        lambda x: (x == "Delivered").sum()
    ),

    # Cancelled orders
    cancelled_orders=(
        "order_status",
        lambda x: (x == "Cancelled").sum()
    ),

    # Failed orders
    failed_orders=(
        "order_status",
        lambda x: (x == "Failed").sum()
    ),

    # Average rating
    average_rating=("customer_rating", "mean")
)

# --------------------------------------------
# Calculate cancellation rate
# --------------------------------------------

meal_period_performance["cancellation_rate"] = (
    meal_period_performance["cancelled_orders"]
    / meal_period_performance["total_orders"]
    * 100
)

# --------------------------------------------
# Calculate failure rate
# --------------------------------------------

meal_period_performance["failure_rate"] = (
    meal_period_performance["failed_orders"]
    / meal_period_performance["total_orders"]
    * 100
)

# --------------------------------------------
# Round values
# --------------------------------------------

meal_period_performance = meal_period_performance.round(2)

# --------------------------------------------
# Display result
# --------------------------------------------

print("MEAL PERIOD PERFORMANCE")
print("=" * 100)

print(meal_period_performance)

MEAL PERIOD PERFORMANCE
====================================================================================================
             total_orders  total_revenue  average_order_value  \
meal_period
Breakfast            5254      910014.30               173.20
Dinner              12558     2183408.00               173.87
Evening              3739      740000.75               197.91
Lunch                8449     1548057.65               183.22

             delivered_orders  cancelled_orders  failed_orders  \
meal_period
Breakfast                4808               315            131
Dinner                  11562               666            330
Evening                  3441               192            106
Lunch                    7772               451            226

             average_rating  cancellation_rate  failure_rate
meal_period
Breakfast              3.98               6.00          2.49
Dinner                 3.99               5.30          2.63
Evening                3.98               5.14          2.83
Lunch                  3.98               5.34          2.67

In [117]:
# ============================================
# STEP 4.24: CUISINE × CUSTOMER SEGMENT PERFORMANCE
# ============================================

cuisine_segment_performance = orders.groupby(
    ["customer_segment", "ordered_cuisine"]
).agg(

    # Total orders
    total_orders=("order_id", "count"),

    # Total revenue
    total_revenue=("order_value", "sum"),

    # Average order value
    average_order_value=("order_value", "mean"),

    # Average rating
    average_rating=("customer_rating", "mean")
).reset_index()

# --------------------------------------------
# Round values
# --------------------------------------------

cuisine_segment_performance = cuisine_segment_performance.round(2)

# --------------------------------------------
# Display result
# --------------------------------------------

print("CUISINE × CUSTOMER SEGMENT PERFORMANCE")
print("=" * 100)

print(cuisine_segment_performance)

CUISINE × CUSTOMER SEGMENT PERFORMANCE
====================================================================================================
        customer_segment ordered_cuisine  total_orders  total_revenue  \
0                 Family         Biryani           778      145085.70
1                 Family         Burgers           366       62353.85
2                 Family            Cafe           245       34968.25
3                 Family         Chinese           633      102658.55
4                 Family        Desserts           476       73323.35
5                 Family         Healthy           517       98902.75
6                 Family           Momos           321       50908.45
7                 Family    North Indian          1396      241844.50
8                 Family           Pizza           739      217829.05
9                 Family    South Indian           777       88893.75
10               Student         Biryani          1090      211612.15
11               Student         Burgers           739      132832.20
12               Student            Cafe           395       52680.05
13               Student         Chinese          1023      167044.30
14               Student        Desserts           571       87299.80
15               Student         Healthy           790      148522.45
16               Student           Momos           801      128839.75
17               Student    North Indian          1405      243151.50
18               Student           Pizza          1110      330333.05
19               Student    South Indian          1097      127133.60
20  Working Professional         Biryani          1108      208634.35
21  Working Professional         Burgers           492       85707.60
22  Working Professional            Cafe           381       52566.15
23  Working Professional         Chinese           958      157141.45
24  Working Professional        Desserts           590       89464.45
25  Working Professional         Healthy           974      186607.80
26  Working Professional           Momos           484       79405.85
27  Working Professional    North Indian          1656      287298.00
28  Working Professional           Pizza           959      277502.95
29  Working Professional    South Indian          1103      127310.65
30    Young Professional         Biryani           685      129580.30
31    Young Professional         Burgers           517       91350.90
32    Young Professional            Cafe           322       43794.40
33    Young Professional         Chinese           642      104895.10
34    Young Professional        Desserts           404       62198.95
35    Young Professional         Healthy           594      112140.85
36    Young Professional           Momos           391       63036.10
37    Young Professional    North Indian           946      160451.00
38    Young Professional           Pizza           811      233850.55
39    Young Professional    South Indian           714       82326.25

    average_order_value  average_rating
0                186.49            3.73
1                170.37            4.00
2                142.73            3.91
3                162.18            4.11
4                154.04            4.02
5                191.30            3.97
6                158.59            3.62
7                173.24            4.01
8                294.76            3.98
9                114.41            4.12
10               194.14            3.74
11               179.75            3.96
12               133.37            4.02
13               163.29            4.14
14               152.89            4.07
15               188.00            3.97
16               160.85            3.61
17               173.06            4.01
18               297.60            4.10
19               115.89            4.09
20               188.30            3.78
21               174.20            3.99
22               137.97            3.91
23               164.03            4.15
24               151.63            4.08
25               191.59            3.97
26               164.06            3.68
27               173.49            4.02
28               289.37            4.06
29               115.42            4.11
30               189.17            3.72
31               176.69            4.01
32               136.01            3.97
33               163.39            4.14
34               153.96            4.01
35               188.79            3.98
36               161.22            3.63
37               169.61            4.02
38               288.35            4.13
39               115.30            4.13

In [118]:
# ============================================
# STEP 4.25: CUSTOMER SEGMENT × MEAL PERIOD
# ============================================

segment_meal_performance = orders.groupby(
    ["customer_segment", "meal_period"]
).agg(

    # Total orders
    total_orders=("order_id", "count"),

    # Total revenue
    total_revenue=("order_value", "sum"),

    # Average order value
    average_order_value=("order_value", "mean"),

    # Average rating
    average_rating=("customer_rating", "mean")
).reset_index()

# --------------------------------------------
# Round values
# --------------------------------------------

segment_meal_performance = segment_meal_performance.round(2)

# --------------------------------------------
# Display result
# --------------------------------------------

print("CUSTOMER SEGMENT × MEAL PERIOD PERFORMANCE")
print("=" * 100)

print(segment_meal_performance)

CUSTOMER SEGMENT × MEAL PERIOD PERFORMANCE
====================================================================================================
        customer_segment meal_period  total_orders  total_revenue  \
0                 Family   Breakfast          1049      182925.55
1                 Family      Dinner          2617      446749.60
2                 Family     Evening           807      162561.25
3                 Family       Lunch          1775      324531.80
4                Student   Breakfast          1594      275638.05
5                Student      Dinner          3538      625146.10
6                Student     Evening          1146      227752.05
7                Student       Lunch          2743      500912.65
8   Working Professional   Breakfast          1540      268104.45
9   Working Professional      Dinner          3657      627635.10
10  Working Professional     Evening          1117      217691.40
11  Working Professional       Lunch          2391      438208.30
12    Young Professional   Breakfast          1071      183346.25
13    Young Professional      Dinner          2746      483877.20
14    Young Professional     Evening           669      131996.05
15    Young Professional       Lunch          1540      284404.90

    average_order_value  average_rating
0                174.38            3.97
1                170.71            3.96
2                201.44            4.00
3                182.83            3.96
4                172.92            3.99
5                176.69            3.98
6                198.74            3.95
7                182.61            3.97
8                174.09            3.97
9                171.63            4.00
10               194.89            4.00
11               183.27            3.99
12               171.19            3.98
13               176.21            3.99
14               197.30            3.99
15               184.68            4.01

In [119]:
# ============================================
# STEP 4.26: DAY × MEAL PERIOD PERFORMANCE
# ============================================

day_meal_performance = orders.groupby(
    ["day_name", "meal_period"]
).agg(

    # Total orders
    total_orders=("order_id", "count"),

    # Total revenue
    total_revenue=("order_value", "sum"),

    # Average order value
    average_order_value=("order_value", "mean"),

    # Average rating
    average_rating=("customer_rating", "mean")
).reset_index()

# --------------------------------------------
# Round values
# --------------------------------------------

day_meal_performance = day_meal_performance.round(2)

# --------------------------------------------
# Display result
# --------------------------------------------

print("DAY × MEAL PERIOD PERFORMANCE")
print("=" * 100)

print(day_meal_performance)

DAY × MEAL PERIOD PERFORMANCE
====================================================================================================
     day_name meal_period  total_orders  total_revenue  average_order_value  \
0      Friday   Breakfast           779      134762.65               172.99
1      Friday      Dinner          1938      333540.60               172.11
2      Friday     Evening           538      105088.60               195.33
3      Friday       Lunch          1260      232826.05               184.78
4      Monday   Breakfast           630      110194.25               174.91
5      Monday      Dinner          1489      263602.35               177.03
6      Monday     Evening           482       97187.15               201.63
7      Monday       Lunch           979      173865.05               177.59
8    Saturday   Breakfast           925      158628.25               171.49
9    Saturday      Dinner          2249      389133.30               173.03
10   Saturday     Evening           603      120065.85               199.11
11   Saturday       Lunch          1600      290431.65               181.52
12     Sunday   Breakfast           875      151923.90               173.63
13     Sunday      Dinner          2134      373226.50               174.90
14     Sunday     Evening           545      110336.35               202.45
15     Sunday       Lunch          1435      262279.70               182.77
16   Thursday   Breakfast           684      115642.55               169.07
17   Thursday      Dinner          1540      265667.75               172.51
18   Thursday     Evening           543      107669.30               198.29
19   Thursday       Lunch          1191      217259.70               182.42
20    Tuesday   Breakfast           625      110771.50               177.23
21    Tuesday      Dinner          1599      275987.75               172.60
22    Tuesday     Evening           473       91537.00               193.52
23    Tuesday       Lunch           940      178425.30               189.81
24  Wednesday   Breakfast           736      128091.20               174.04
25  Wednesday      Dinner          1609      282249.75               175.42
26  Wednesday     Evening           555      108116.50               194.80
27  Wednesday       Lunch          1044      192970.20               184.84

    average_rating
0             4.00
1             3.95
2             3.97
3             4.01
4             4.05
5             4.00
6             3.99
7             3.97
8             3.92
9             3.98
10            3.95
11            4.00
12            3.96
13            4.00
14            3.99
15            3.97
16            3.97
17            3.97
18            4.03
19            3.99
20            4.02
21            4.00
22            3.94
23            3.95
24            3.96
25            3.98
26            3.98
27            3.97

In [120]:
# ============================================
# STEP 4.27: RESTAURANT PERFORMANCE
# ============================================

restaurant_performance = orders.groupby("restaurant_id").agg(

    # Total orders
    total_orders=("order_id", "count"),

    # Total revenue
    total_revenue=("order_value", "sum"),

    # Average order value
    average_order_value=("order_value", "mean"),

    # Delivered orders
    delivered_orders=(
        "order_status",
        lambda x: (x == "Delivered").sum()
    ),

    # Cancelled orders
    cancelled_orders=(
        "order_status",
        lambda x: (x == "Cancelled").sum()
    ),

    # Failed orders
    failed_orders=(
        "order_status",
        lambda x: (x == "Failed").sum()
    ),

    # Average rating
    average_rating=("customer_rating", "mean")
).reset_index()

# --------------------------------------------
# Calculate cancellation rate
# --------------------------------------------

restaurant_performance["cancellation_rate"] = (
    restaurant_performance["cancelled_orders"]
    / restaurant_performance["total_orders"]
    * 100
)

# --------------------------------------------
# Calculate failure rate
# --------------------------------------------

restaurant_performance["failure_rate"] = (
    restaurant_performance["failed_orders"]
    / restaurant_performance["total_orders"]
    * 100
)

# --------------------------------------------
# Round values
# --------------------------------------------

restaurant_performance = restaurant_performance.round(2)

# --------------------------------------------
# Top 20 restaurants by revenue (separate view,
# does NOT overwrite restaurant_performance)
# --------------------------------------------

restaurant_performance_by_revenue = restaurant_performance.sort_values(
    "total_revenue",
    ascending=False
)

print("TOP 20 RESTAURANTS BY REVENUE")
print("=" * 100)

print(restaurant_performance_by_revenue.head(20))

TOP 20 RESTAURANTS BY REVENUE
====================================================================================================
    restaurant_id  total_orders  total_revenue  average_order_value  \
55           R056           591      150095.50               253.97
73           R074           574      105662.70               184.08
92           R093           317      101035.70               318.72
17           R018           374       90556.30               242.13
95           R096           444       84598.25               190.54
138          R139           427       84359.20               197.56
63           R064           215       75528.00               351.29
36           R037           405       72627.70               179.33
110          R111           436       70884.80               162.58
47           R048           228       70039.55               307.19
80           R081           222       68832.00               310.05
115          R116           197       67734.00               343.83
23           R024           477       67712.60               141.96
70           R071           348       66738.95               191.78
136          R137           479       66703.60               139.26
120          R121           205       66568.35               324.72
13           R014           207       64864.00               313.35
24           R025           386       63636.10               164.86
43           R044           356       61130.00               171.71
31           R032           319       60121.05               188.47

     delivered_orders  cancelled_orders  failed_orders  average_rating  \
55                557                24             10            4.53
73                541                15             18            4.58
92                301                11              5            4.70
17                353                15              6            3.70
95                413                22              9            4.48
138               333                59             35            4.69
63                201                 9              5            3.11
36                384                12              9            4.58
110               417                11              8            4.69
47                220                 3              5            3.15
80                211                 8              3            3.94
115               188                 5              4            4.32
23                453                17              7            4.26
70                325                15              8            3.76
136               388                58             33            4.29
120               196                 7              2            4.19
13                197                 7              3            4.63
24                357                22              7            4.13
43                334                14              8            4.76
31                301                11              7            4.14

     cancellation_rate  failure_rate
55                4.06          1.69
73                2.61          3.14
92                3.47          1.58
17                4.01          1.60
95                4.95          2.03
138              13.82          8.20
63                4.19          2.33
36                2.96          2.22
110               2.52          1.83
47                1.32          2.19
80                3.60          1.35
115               2.54          2.03
23                3.56          1.47
70                4.31          2.30
136              12.11          6.89
120               3.41          0.98
13                3.38          1.45
24                5.70          1.81
43                3.93          2.25
31                3.45          2.19

In [121]:
# ============================================
# STEP 4.28: PLATFORM × CUSTOMER SEGMENT PERFORMANCE
# ============================================

platform_segment_performance = orders.groupby(
    ["customer_segment", "platform"]
).agg(

    # Total orders
    total_orders=("order_id", "count"),

    # Total revenue
    total_revenue=("order_value", "sum"),

    # Average order value
    average_order_value=("order_value", "mean"),

    # Delivered orders
    delivered_orders=(
        "order_status",
        lambda x: (x == "Delivered").sum()
    ),

    # Cancelled orders
    cancelled_orders=(
        "order_status",
        lambda x: (x == "Cancelled").sum()
    ),

    # Failed orders
    failed_orders=(
        "order_status",
        lambda x: (x == "Failed").sum()
    ),

    # Average rating
    average_rating=("customer_rating", "mean")
).reset_index()

# --------------------------------------------
# Calculate cancellation rate
# --------------------------------------------

platform_segment_performance["cancellation_rate"] = (
    platform_segment_performance["cancelled_orders"]
    / platform_segment_performance["total_orders"]
    * 100
)

# --------------------------------------------
# Calculate failure rate
# --------------------------------------------

platform_segment_performance["failure_rate"] = (
    platform_segment_performance["failed_orders"]
    / platform_segment_performance["total_orders"]
    * 100
)

# --------------------------------------------
# Round values
# --------------------------------------------

platform_segment_performance = platform_segment_performance.round(2)

# --------------------------------------------
# Display result
# --------------------------------------------

print("PLATFORM × CUSTOMER SEGMENT PERFORMANCE")
print("=" * 100)

print(platform_segment_performance)

PLATFORM × CUSTOMER SEGMENT PERFORMANCE
====================================================================================================
        customer_segment platform  total_orders  total_revenue  \
0                 Family   Direct           609      104279.90
1                 Family   Swiggy          2787      509415.55
2                 Family   Zomato          2852      503072.75
3                Student   Direct           880      155756.20
4                Student   Swiggy          4043      744113.50
5                Student   Zomato          4098      729579.15
6   Working Professional   Direct           870      151180.05
7   Working Professional   Swiggy          3931      713698.70
8   Working Professional   Zomato          3904      686760.50
9     Young Professional   Direct           631      111318.05
10    Young Professional   Swiggy          2732      500657.85
11    Young Professional   Zomato          2663      471648.50

    average_order_value  delivered_orders  cancelled_orders  failed_orders  \
0                171.23               440               114             55
1                182.78              2627               101             59
2                176.39              2692               107             53
3                177.00               609               192             79
4                184.05              3815               146             82
5                178.03              3870               153             75
6                173.77               612               162             96
7                181.56              3673               185             73
8                175.91              3676               163             65
9                176.42               483                94             54
10               183.26              2574                99             59
11               177.11              2512               108             43

    average_rating  cancellation_rate  failure_rate
0             4.03              18.72          9.03
1             4.02               3.62          2.12
2             3.91               3.75          1.86
3             4.00              21.82          8.98
4             4.03               3.61          2.03
5             3.92               3.73          1.83
6             4.05              18.62         11.03
7             4.05               4.71          1.86
8             3.93               4.18          1.66
9             3.98              14.90          8.56
10            4.03               3.62          2.16
11            3.95               4.06          1.61

In [122]:
# ============================================
# STEP 4.29: PLATFORM × CUISINE PERFORMANCE
# ============================================

platform_cuisine = orders.groupby(
    ["platform", "ordered_cuisine"]
).agg(

    # Total orders
    total_orders=("order_id", "count"),

    # Total revenue
    total_revenue=("order_value", "sum"),

    # Average order value
    average_order_value=("order_value", "mean"),

    # Delivered orders
    delivered_orders=(
        "order_status",
        lambda x: (x == "Delivered").sum()
    ),

    # Cancelled orders
    cancelled_orders=(
        "order_status",
        lambda x: (x == "Cancelled").sum()
    ),

    # Failed orders
    failed_orders=(
        "order_status",
        lambda x: (x == "Failed").sum()
    ),

    # Average rating
    average_rating=("customer_rating", "mean")
).reset_index()


# --------------------------------------------
# Calculate cancellation rate
# --------------------------------------------

platform_cuisine["cancellation_rate"] = (
    platform_cuisine["cancelled_orders"]
    / platform_cuisine["total_orders"]
    * 100
)


# --------------------------------------------
# Calculate failure rate
# --------------------------------------------

platform_cuisine["failure_rate"] = (
    platform_cuisine["failed_orders"]
    / platform_cuisine["total_orders"]
    * 100
)


# --------------------------------------------
# Round values
# --------------------------------------------

platform_cuisine[
    [
        "total_revenue",
        "average_order_value",
        "average_rating",
        "cancellation_rate",
        "failure_rate"
    ]
] = platform_cuisine[
    [
        "total_revenue",
        "average_order_value",
        "average_rating",
        "cancellation_rate",
        "failure_rate"
    ]
].round(2)


# --------------------------------------------
# Display results
# --------------------------------------------

print("PLATFORM × CUISINE PERFORMANCE")
print("=" * 100)

print(platform_cuisine)

PLATFORM × CUISINE PERFORMANCE
====================================================================================================
   platform ordered_cuisine  total_orders  total_revenue  average_order_value  \
0    Direct         Biryani           456       87181.05               191.19
1    Direct         Burgers           537       97785.15               182.10
2    Direct         Chinese           296       41046.20               138.67
3    Direct        Desserts           131       15832.60               120.86
4    Direct         Healthy           168       37959.20               225.95
5    Direct           Momos            27        4500.10               166.67
6    Direct    North Indian           839      158426.95               188.83
7    Direct           Pizza           121       30093.95               248.71
8    Direct    South Indian           415       49709.00               119.78
9    Swiggy         Biryani          1693      320801.60               189.49
10   Swiggy         Burgers           382       65382.90               171.16
11   Swiggy            Cafe           682       84200.95               123.46
12   Swiggy         Chinese          1906      314622.70               165.07
13   Swiggy        Desserts          1410      212700.40               150.85
14   Swiggy         Healthy          1609      308966.80               192.02
15   Swiggy           Momos           999      156484.65               156.64
16   Swiggy    North Indian          1747      323024.00               184.90
17   Swiggy           Pizza          1727      533543.45               308.94
18   Swiggy    South Indian          1338      148158.15               110.73
19   Zomato         Biryani          1512      286929.85               189.77
20   Zomato         Burgers          1195      209076.50               174.96
21   Zomato            Cafe           661       99807.90               151.00
22   Zomato         Chinese          1054      176070.50               167.05
23   Zomato        Desserts           500       83753.55               167.51
24   Zomato         Healthy          1098      199247.85               181.46
25   Zomato           Momos           971      161205.40               166.02
26   Zomato    North Indian          2817      451294.05               160.20
27   Zomato           Pizza          1771      495878.20               280.00
28   Zomato    South Indian          1938      227797.10               117.54

    delivered_orders  cancelled_orders  failed_orders  average_rating  \
0                317                89             50            3.95
1                388               103             46            3.85
2                216                50             30            4.29
3                 91                28             12            4.20
4                124                29             15            3.90
5                 20                 5              2            3.25
6                617               143             79            4.17
7                 83                26             12            4.05
8                288                89             38            3.82
9               1596                67             30            3.69
10               356                19              7            4.07
11               634                30             18            4.05
12              1804                61             41            4.39
13              1322                66             22            3.95
14              1512                66             31            3.96
15               945                34             20            3.63
16              1627                77             43            4.05
17              1633                61             33            4.13
18              1260                50             28            4.26
19              1413                67             32            3.76
20              1131                38             26            4.01
21               638                17              6            3.87
22               996                40             18            3.65
23               473                17             10            4.30
24              1026                58             14            4.00
25               917                41             13            3.64
26              2658               111             48            3.96
27              1672                63             36            4.02
28              1826                79             33            4.05

    cancellation_rate  failure_rate
0               19.52         10.96
1               19.18          8.57
2               16.89         10.14
3               21.37          9.16
4               17.26          8.93
5               18.52          7.41
6               17.04          9.42
7               21.49          9.92
8               21.45          9.16
9                3.96          1.77
10               4.97          1.83
11               4.40          2.64
12               3.20          2.15
13               4.68          1.56
14               4.10          1.93
15               3.40          2.00
16               4.41          2.46
17               3.53          1.91
18               3.74          2.09
19               4.43          2.12
20               3.18          2.18
21               2.57          0.91
22               3.80          1.71
23               3.40          2.00
24               5.28          1.28
25               4.22          1.34
26               3.94          1.70
27               3.56          2.03
28               4.08          1.70

In [123]:
# ============================================
# STEP 4.30: TOP PLATFORM × CUISINE COMBINATIONS
# ============================================

top_platform_cuisine = platform_cuisine.sort_values(
    "total_revenue",
    ascending=False
).head(10)

print("TOP 10 PLATFORM × CUISINE COMBINATIONS BY REVENUE")
print("=" * 100)

print(top_platform_cuisine[
    [
        "platform",
        "ordered_cuisine",
        "total_orders",
        "total_revenue",
        "average_order_value",
        "average_rating",
        "cancellation_rate",
        "failure_rate"
    ]
].to_string(index=False))

TOP 10 PLATFORM × CUISINE COMBINATIONS BY REVENUE
====================================================================================================
platform ordered_cuisine  total_orders  total_revenue  average_order_value  average_rating  cancellation_rate  failure_rate
  Swiggy           Pizza          1727      533543.45               308.94            4.13               3.53          1.91
  Zomato           Pizza          1771      495878.20               280.00            4.02               3.56          2.03
  Zomato    North Indian          2817      451294.05               160.20            3.96               3.94          1.70
  Swiggy    North Indian          1747      323024.00               184.90            4.05               4.41          2.46
  Swiggy         Biryani          1693      320801.60               189.49            3.69               3.96          1.77
  Swiggy         Chinese          1906      314622.70               165.07            4.39               3.20          2.15
  Swiggy         Healthy          1609      308966.80               192.02            3.96               4.10          1.93
  Zomato         Biryani          1512      286929.85               189.77            3.76               4.43          2.12
  Zomato    South Indian          1938      227797.10               117.54            4.05               4.08          1.70
  Swiggy        Desserts          1410      212700.40               150.85            3.95               4.68          1.56

In [124]:
# ============================================
# STEP 4.31: TOP PLATFORM × CUISINE BY ORDERS
# ============================================

top_platform_cuisine_orders = platform_cuisine.sort_values(
    "total_orders",
    ascending=False
).head(10)

print("TOP 10 PLATFORM × CUISINE COMBINATIONS BY ORDERS")
print("=" * 100)

print(
    top_platform_cuisine_orders[
        [
            "platform",
            "ordered_cuisine",
            "total_orders",
            "total_revenue",
            "average_order_value",
            "average_rating",
            "cancellation_rate",
            "failure_rate"
        ]
    ].to_string(index=False)
)

TOP 10 PLATFORM × CUISINE COMBINATIONS BY ORDERS
====================================================================================================
platform ordered_cuisine  total_orders  total_revenue  average_order_value  average_rating  cancellation_rate  failure_rate
  Zomato    North Indian          2817      451294.05               160.20            3.96               3.94          1.70
  Zomato    South Indian          1938      227797.10               117.54            4.05               4.08          1.70
  Swiggy         Chinese          1906      314622.70               165.07            4.39               3.20          2.15
  Zomato           Pizza          1771      495878.20               280.00            4.02               3.56          2.03
  Swiggy    North Indian          1747      323024.00               184.90            4.05               4.41          2.46
  Swiggy           Pizza          1727      533543.45               308.94            4.13               3.53          1.91
  Swiggy         Biryani          1693      320801.60               189.49            3.69               3.96          1.77
  Swiggy         Healthy          1609      308966.80               192.02            3.96               4.10          1.93
  Zomato         Biryani          1512      286929.85               189.77            3.76               4.43          2.12
  Swiggy        Desserts          1410      212700.40               150.85            3.95               4.68          1.56

In [125]:
# ============================================
# STEP 4.32: CUISINE × MEAL PERIOD PERFORMANCE
# ============================================

cuisine_meal = orders.groupby(
    ["ordered_cuisine", "meal_period"]
).agg(

    total_orders=("order_id", "count"),

    total_revenue=("order_value", "sum"),

    average_order_value=("order_value", "mean"),

    delivered_orders=(
        "order_status",
        lambda x: (x == "Delivered").sum()
    ),

    cancelled_orders=(
        "order_status",
        lambda x: (x == "Cancelled").sum()
    ),

    failed_orders=(
        "order_status",
        lambda x: (x == "Failed").sum()
    ),

    average_rating=("customer_rating", "mean")

).reset_index()


# --------------------------------------------
# Calculate cancellation rate
# --------------------------------------------

cuisine_meal["cancellation_rate"] = (
    cuisine_meal["cancelled_orders"]
    / cuisine_meal["total_orders"]
    * 100
)


# --------------------------------------------
# Calculate failure rate
# --------------------------------------------

cuisine_meal["failure_rate"] = (
    cuisine_meal["failed_orders"]
    / cuisine_meal["total_orders"]
    * 100
)


# --------------------------------------------
# Round values
# --------------------------------------------

cuisine_meal[
    [
        "total_revenue",
        "average_order_value",
        "average_rating",
        "cancellation_rate",
        "failure_rate"
    ]
] = cuisine_meal[
    [
        "total_revenue",
        "average_order_value",
        "average_rating",
        "cancellation_rate",
        "failure_rate"
    ]
].round(2)


# --------------------------------------------
# Display results
# --------------------------------------------

print("CUISINE × MEAL PERIOD PERFORMANCE")
print("=" * 100)

print(cuisine_meal.to_string(index=False))

CUISINE × MEAL PERIOD PERFORMANCE
====================================================================================================
ordered_cuisine meal_period  total_orders  total_revenue  average_order_value  delivered_orders  cancelled_orders  failed_orders  average_rating  cancellation_rate  failure_rate
        Biryani   Breakfast           639      138271.40               216.39               579                40             20            3.77               6.26          3.13
        Biryani      Dinner          1507      265719.70               176.32              1373                87             47            3.73               5.77          3.12
        Biryani     Evening           475       79638.05               167.66               422                32             21            3.74               6.74          4.42
        Biryani       Lunch          1040      211283.35               203.16               952                64             24            3.76               6.15          2.31
        Burgers   Breakfast           375       52814.75               140.84               329                34             12            3.95               9.07          3.20
        Burgers      Dinner           903      156031.20               172.79               801                64             38            4.00               7.09          4.21
        Burgers     Evening           275       59422.25               216.08               249                17              9            4.02               6.18          3.27
        Burgers       Lunch           561      103976.35               185.34               496                45             20            3.97               8.02          3.57
           Cafe   Breakfast           233       27916.10               119.81               220                11              2            3.95               4.72          0.86
           Cafe      Dinner           575       93217.75               162.12               550                13             12            3.99               2.26          2.09
           Cafe     Evening           172       25318.00               147.20               160                10              2            3.93               5.81          1.16
           Cafe       Lunch           363       37557.00               103.46               342                13              8            3.91               3.58          2.20
        Chinese   Breakfast           579       87797.80               151.64               540                30              9            4.19               5.18          1.55
        Chinese      Dinner          1348      221030.20               163.97              1255                57             36            4.16               4.23          2.67
        Chinese     Evening           389       68812.35               176.90               350                26             13            4.11               6.68          3.34
        Chinese       Lunch           940      154099.05               163.94               871                38             31            4.09               4.04          3.30
       Desserts   Breakfast           351       38664.80               110.16               320                25              6            4.00               7.12          1.71
       Desserts      Dinner           870      130847.20               150.40               811                41             18            4.06               4.71          2.07
       Desserts     Evening           259       50517.80               195.05               236                16              7            4.07               6.18          2.70
       Desserts       Lunch           561       92256.75               164.45               519                29             13            4.06               5.17          2.32
        Healthy   Breakfast           501       92811.85               185.25               463                29              9            3.97               5.79          1.80
        Healthy      Dinner          1196      199754.95               167.02              1103                65             28            3.96               5.43          2.34
        Healthy     Evening           355       79628.60               224.31               334                15              6            3.94               4.23          1.69
        Healthy       Lunch           823      173978.45               211.40               762                44             17            4.01               5.35          2.07
          Momos   Breakfast           355       44458.70               125.24               339                11              5            3.60               3.10          1.41
          Momos      Dinner           827      152075.05               183.89               774                39             14            3.64               4.72          1.69
          Momos     Evening           258       42900.15               166.28               248                 3              7            3.56               1.16          2.71
          Momos       Lunch           557       82756.25               148.57               521                27              9            3.67               4.85          1.62
   North Indian   Breakfast           921      202204.30               219.55               823                63             35            4.00               6.84          3.80
   North Indian      Dinner          2224      312811.50               140.65              2032               135             57            4.03               6.07          2.56
   North Indian     Evening           671      141857.70               211.41               609                43             19            4.03               6.41          2.83
   North Indian       Lunch          1587      275871.50               173.83              1438                90             59            4.00               5.67          3.72
          Pizza   Breakfast           652      152568.45               234.00               601                31             20            4.10               4.75          3.07
          Pizza      Dinner          1507      451321.90               299.48              1408                67             32            4.06               4.45          2.12
          Pizza     Evening           407      135304.55               332.44               379                17             11            4.07               4.18          2.70
          Pizza       Lunch          1053      320320.70               304.20              1000                35             18            4.09               3.32          1.71
   South Indian   Breakfast           648       72506.15               111.89               594                41             13            4.09               6.33          2.01
   South Indian      Dinner          1601      200598.55               125.30              1455                98             48            4.10               6.12          3.00
   South Indian     Evening           478       56601.30               118.41               454                13             11            4.16               2.72          2.30
   South Indian       Lunch           964       95958.25                99.54               871                66             27            4.13               6.85          2.80

In [126]:
# ============================================
# STEP 4.33: CUISINE PERFORMANCE SUMMARY
# ============================================

cuisine_performance = (
    orders.groupby("ordered_cuisine")
    .agg(
        total_orders=("order_id", "count"),
        total_revenue=("order_value", "sum"),
        average_order_value=("order_value", "mean"),
        delivered_orders=(
            "order_status",
            lambda x: (x == "Delivered").sum()
        ),
        cancelled_orders=(
            "order_status",
            lambda x: (x == "Cancelled").sum()
        ),
        failed_orders=(
            "order_status",
            lambda x: (x == "Failed").sum()
        ),
        average_rating=("customer_rating", "mean")
    )
)

cuisine_performance["cancellation_rate"] = (
    cuisine_performance["cancelled_orders"]
    / cuisine_performance["total_orders"]
    * 100
)

cuisine_performance["failure_rate"] = (
    cuisine_performance["failed_orders"]
    / cuisine_performance["total_orders"]
    * 100
)

cuisine_performance = cuisine_performance.round(2)

print("CUISINE PERFORMANCE SUMMARY")
print("=" * 100)
print(cuisine_performance)

CUISINE PERFORMANCE SUMMARY
====================================================================================================
                 total_orders  total_revenue  average_order_value  \
ordered_cuisine
Biryani                  3661      694912.50               189.81
Burgers                  2114      372244.55               176.09
Cafe                     1343      184008.85               137.01
Chinese                  3256      531739.40               163.31
Desserts                 2041      312286.55               153.01
Healthy                  2875      546173.85               189.97
Momos                    1997      322190.15               161.34
North Indian             5403      932745.00               172.63
Pizza                    3619     1059515.60               292.76
South Indian             3691      425664.25               115.32

                 delivered_orders  cancelled_orders  failed_orders  \
ordered_cuisine
Biryani                      3326               223            112
Burgers                      1875               160             79
Cafe                         1272                47             24
Chinese                      3016               151             89
Desserts                     1886               111             44
Healthy                      2662               153             60
Momos                        1882                80             35
North Indian                 4902               331            170
Pizza                        3388               150             81
South Indian                 3374               218             99

                 average_rating  cancellation_rate  failure_rate
ordered_cuisine
Biryani                    3.75               6.09          3.06
Burgers                    3.99               7.57          3.74
Cafe                       3.96               3.50          1.79
Chinese                    4.14               4.64          2.73
Desserts                   4.05               5.44          2.16
Healthy                    3.97               5.32          2.09
Momos                      3.63               4.01          1.75
North Indian               4.02               6.13          3.15
Pizza                      4.08               4.14          2.24
South Indian               4.11               5.91          2.68

In [127]:
# ============================================
# STEP 4.34: TOP 10 RESTAURANTS BY ORDERS
# ============================================

top_restaurants_orders = (
    restaurant_performance
    .sort_values("total_orders", ascending=False)
    .head(10)
)

print("TOP 10 RESTAURANTS BY ORDER VOLUME")
print("=" * 100)
print(top_restaurants_orders)

TOP 10 RESTAURANTS BY ORDER VOLUME
====================================================================================================
    restaurant_id  total_orders  total_revenue  average_order_value  \
55           R056           591      150095.50               253.97
73           R074           574      105662.70               184.08
136          R137           479       66703.60               139.26
23           R024           477       67712.60               141.96
112          R113           465       48017.20               103.26
95           R096           444       84598.25               190.54
110          R111           436       70884.80               162.58
138          R139           427       84359.20               197.56
36           R037           405       72627.70               179.33
75           R076           401       46674.00               116.39

     delivered_orders  cancelled_orders  failed_orders  average_rating  \
55                557                24             10            4.53
73                541                15             18            4.58
136               388                58             33            4.29
23                453                17              7            4.26
112               444                12              9            4.52
95                413                22              9            4.48
110               417                11              8            4.69
138               333                59             35            4.69
36                384                12              9            4.58
75                381                16              4            3.52

     cancellation_rate  failure_rate
55                4.06          1.69
73                2.61          3.14
136              12.11          6.89
23                3.56          1.47
112               2.58          1.94
95                4.95          2.03
110               2.52          1.83
138              13.82          8.20
36                2.96          2.22
75                3.99          1.00

In [128]:
# ============================================
# STEP 4.35: CUSTOMER ORDERING BEHAVIOR
# ============================================

customer_behavior = (
    orders
    .groupby("customer_id")
    .agg(
        # Total orders placed by customer
        total_orders=("order_id", "count"),

        # Total revenue generated by customer
        total_revenue=("order_value", "sum"),

        # Average order value
        average_order_value=("order_value", "mean"),

        # Number of delivered orders
        delivered_orders=(
            "order_status",
            lambda x: (x == "Delivered").sum()
        ),

        # Number of cancelled orders
        cancelled_orders=(
            "order_status",
            lambda x: (x == "Cancelled").sum()
        ),

        # Number of failed orders
        failed_orders=(
            "order_status",
            lambda x: (x == "Failed").sum()
        ),

        # Average customer rating given
        average_rating=("customer_rating", "mean"),

        # Preferred customer segment
        customer_segment=("customer_segment", "first"),

        # Customer locality
        locality_id=("locality_id", "first")
    )
)

# --------------------------------------------
# Calculate cancellation rate
# --------------------------------------------

customer_behavior["cancellation_rate"] = (
    customer_behavior["cancelled_orders"]
    / customer_behavior["total_orders"]
    * 100
)

# --------------------------------------------
# Calculate failure rate
# --------------------------------------------

customer_behavior["failure_rate"] = (
    customer_behavior["failed_orders"]
    / customer_behavior["total_orders"]
    * 100
)

# --------------------------------------------
# Calculate delivery success rate
# --------------------------------------------

customer_behavior["delivery_success_rate"] = (
    customer_behavior["delivered_orders"]
    / customer_behavior["total_orders"]
    * 100
)

# --------------------------------------------
# Round numerical values
# --------------------------------------------

customer_behavior = customer_behavior.round({
    "total_revenue": 2,
    "average_order_value": 2,
    "average_rating": 2,
    "cancellation_rate": 2,
    "failure_rate": 2,
    "delivery_success_rate": 2
})

# --------------------------------------------
# Display customer behavior
# --------------------------------------------

print("CUSTOMER ORDERING BEHAVIOR")
print("=" * 100)

print(customer_behavior.head(20))

CUSTOMER ORDERING BEHAVIOR
====================================================================================================
             total_orders  total_revenue  average_order_value  \
customer_id
C00001                  5         729.45               145.89
C00002                 19        4105.65               216.09
C00003                  4         561.90               140.48
C00004                  7        1114.60               159.23
C00005                  2         345.80               172.90
C00006                  2         393.75               196.88
C00007                  5        1101.95               220.39
C00008                 11        2067.10               187.92
C00009                  2         306.90               153.45
C00010                  5         666.60               133.32
C00012                  9        1211.00               134.56
C00013                  2         420.40               210.20
C00014                  3         669.70               223.23
C00015                  2         230.35               115.18
C00016                  4         798.35               199.59
C00017                  4         744.90               186.22
C00018                  9        1485.35               165.04
C00019                  3         490.45               163.48
C00020                  2         224.50               112.25
C00021                  7        1298.65               185.52

             delivered_orders  cancelled_orders  failed_orders  \
customer_id
C00001                      5                 0              0
C00002                     17                 1              1
C00003                      4                 0              0
C00004                      7                 0              0
C00005                      2                 0              0
C00006                      2                 0              0
C00007                      5                 0              0
C00008                     10                 1              0
C00009                      1                 1              0
C00010                      5                 0              0
C00012                      9                 0              0
C00013                      2                 0              0
C00014                      3                 0              0
C00015                      2                 0              0
C00016                      3                 0              1
C00017                      4                 0              0
C00018                      6                 3              0
C00019                      3                 0              0
C00020                      2                 0              0
C00021                      7                 0              0

             average_rating      customer_segment  locality_id  \
customer_id
C00001                 4.40                Family            7
C00002                 3.82  Working Professional            4
C00003                 4.00               Student            8
C00004                 3.86               Student            5
C00005                 3.00               Student            7
C00006                 4.50    Young Professional           10
C00007                 4.00  Working Professional            3
C00008                 4.00                Family            7
C00009                 4.00  Working Professional            8
C00010                 4.40  Working Professional            5
C00012                 4.00               Student            8
C00013                 4.00    Young Professional            8
C00014                 4.33  Working Professional            3
C00015                 3.50  Working Professional            6
C00016                 4.67    Young Professional            5
C00017                 4.00               Student            2
C00018                 4.50    Young Professional            8
C00019                 4.67  Working Professional            6
C00020                 3.00  Working Professional            2
C00021                 4.71  Working Professional            5

             cancellation_rate  failure_rate  delivery_success_rate
customer_id
C00001                    0.00          0.00                 100.00
C00002                    5.26          5.26                  89.47
C00003                    0.00          0.00                 100.00
C00004                    0.00          0.00                 100.00
C00005                    0.00          0.00                 100.00
C00006                    0.00          0.00                 100.00
C00007                    0.00          0.00                 100.00
C00008                    9.09          0.00                  90.91
C00009                   50.00          0.00                  50.00
C00010                    0.00          0.00                 100.00
C00012                    0.00          0.00                 100.00
C00013                    0.00          0.00                 100.00
C00014                    0.00          0.00                 100.00
C00015                    0.00          0.00                 100.00
C00016                    0.00         25.00                  75.00
C00017                    0.00          0.00                 100.00
C00018                   33.33          0.00                  66.67
C00019                    0.00          0.00                 100.00
C00020                    0.00          0.00                 100.00
C00021                    0.00          0.00                 100.00

In [129]:
# ============================================
# STEP 4.36: CUSTOMER BEHAVIOR SEGMENTATION
# ============================================

def classify_customer(row):

    orders_count = row["total_orders"]
    revenue = row["total_revenue"]
    success_rate = row["delivery_success_rate"]

    # High-value loyal customers
    if orders_count >= 10 and revenue >= 1800:
        return "High Value Loyal"

    # Frequent customers
    elif orders_count >= 8:
        return "Frequent Customer"

    # High spenders with fewer orders
    elif revenue >= 1500:
        return "High Value Occasional"

    # Regular customers with good delivery success
    elif orders_count >= 4 and success_rate >= 90:
        return "Regular Customer"

    # Low activity customers
    else:
        return "Low Activity"


# --------------------------------------------
# Assign behavioral segment
# --------------------------------------------

customer_behavior["behavior_segment"] = (
    customer_behavior.apply(
        classify_customer,
        axis=1
    )
)


# --------------------------------------------
# Display customer behavior segments
# --------------------------------------------

print("CUSTOMER BEHAVIOR SEGMENTATION")
print("=" * 100)

print(
    customer_behavior[
        [
            "total_orders",
            "total_revenue",
            "average_order_value",
            "delivery_success_rate",
            "behavior_segment"
        ]
    ].head(20)
)


# --------------------------------------------
# Segment distribution
# --------------------------------------------

print("\n\nBEHAVIOR SEGMENT DISTRIBUTION")
print("=" * 100)

print(
    customer_behavior["behavior_segment"]
    .value_counts()
)


# --------------------------------------------
# Segment performance
# --------------------------------------------

behavior_segment_summary = (
    customer_behavior
    .groupby("behavior_segment")
    .agg(
        customers=("total_orders", "count"),

        total_orders=("total_orders", "sum"),

        total_revenue=("total_revenue", "sum"),

        average_orders=("total_orders", "mean"),

        average_revenue=("total_revenue", "mean"),

        average_order_value=("average_order_value", "mean"),

        average_rating=("average_rating", "mean"),

        average_delivery_success=(
            "delivery_success_rate",
            "mean"
        )
    )
    .sort_values(
        "total_revenue",
        ascending=False
    )
    .round(2)
)


# --------------------------------------------
# Display segment performance
# --------------------------------------------

print("\n\nBEHAVIOR SEGMENT PERFORMANCE")
print("=" * 100)

print(behavior_segment_summary)

CUSTOMER BEHAVIOR SEGMENTATION
====================================================================================================
             total_orders  total_revenue  average_order_value  \
customer_id
C00001                  5         729.45               145.89
C00002                 19        4105.65               216.09
C00003                  4         561.90               140.48
C00004                  7        1114.60               159.23
C00005                  2         345.80               172.90
C00006                  2         393.75               196.88
C00007                  5        1101.95               220.39
C00008                 11        2067.10               187.92
C00009                  2         306.90               153.45
C00010                  5         666.60               133.32
C00012                  9        1211.00               134.56
C00013                  2         420.40               210.20
C00014                  3         669.70               223.23
C00015                  2         230.35               115.18
C00016                  4         798.35               199.59
C00017                  4         744.90               186.22
C00018                  9        1485.35               165.04
C00019                  3         490.45               163.48
C00020                  2         224.50               112.25
C00021                  7        1298.65               185.52

             delivery_success_rate   behavior_segment
customer_id
C00001                      100.00   Regular Customer
C00002                       89.47   High Value Loyal
C00003                      100.00   Regular Customer
C00004                      100.00   Regular Customer
C00005                      100.00       Low Activity
C00006                      100.00       Low Activity
C00007                      100.00   Regular Customer
C00008                       90.91   High Value Loyal
C00009                       50.00       Low Activity
C00010                      100.00   Regular Customer
C00012                      100.00  Frequent Customer
C00013                      100.00       Low Activity
C00014                      100.00       Low Activity
C00015                      100.00       Low Activity
C00016                       75.00       Low Activity
C00017                      100.00   Regular Customer
C00018                       66.67  Frequent Customer
C00019                      100.00       Low Activity
C00020                      100.00       Low Activity
C00021                      100.00   Regular Customer


BEHAVIOR SEGMENT DISTRIBUTION
====================================================================================================
behavior_segment
Low Activity             2217
Regular Customer         1251
High Value Loyal          735
Frequent Customer         647
High Value Occasional      64
Name: count, dtype: int64


BEHAVIOR SEGMENT PERFORMANCE
====================================================================================================
                       customers  total_orders  total_revenue  average_orders  \
behavior_segment
High Value Loyal             735         10234     1892778.10           13.92
Low Activity                2217          7149     1268393.20            3.22
Regular Customer            1251          6383     1124072.95            5.10
Frequent Customer            647          5798      989894.25            8.96
High Value Occasional         64           436      106342.20            6.81

                       average_revenue  average_order_value  average_rating  \
behavior_segment
High Value Loyal               2575.21               185.74            3.99
Low Activity                    572.12               178.10            3.97
Regular Customer                898.54               176.63            3.99
Frequent Customer              1529.98               172.03            3.98
High Value Occasional          1661.60               244.93            4.02

                       average_delivery_success
behavior_segment
High Value Loyal                          91.77
Low Activity                              87.45
Regular Customer                         100.00
Frequent Customer                         92.44
High Value Occasional                     94.12

In [130]:
# ============================================
# STEP 4.37 — CUSTOMER PURCHASE FREQUENCY & RECENCY
# ============================================

# Make sure order_date is datetime
orders["order_date"] = pd.to_datetime(orders["order_date"])

# Latest date in the dataset
latest_order_date = orders["order_date"].max()

print("Latest order date:", latest_order_date)

# --------------------------------------------
# Customer purchase behavior
# --------------------------------------------

customer_frequency = (
    orders
    .groupby("customer_id")
    .agg(
        first_order_date=("order_date", "min"),
        last_order_date=("order_date", "max"),
        total_orders=("order_id", "nunique"),
        total_revenue=("order_value", "sum")
    )
)

# --------------------------------------------
# Recency
# --------------------------------------------

customer_frequency["recency_days"] = (
    latest_order_date - customer_frequency["last_order_date"]
).dt.days

# --------------------------------------------
# Customer lifetime
# --------------------------------------------

customer_frequency["customer_lifetime_days"] = (
    customer_frequency["last_order_date"]
    - customer_frequency["first_order_date"]
).dt.days

# --------------------------------------------
# Average days between orders
# --------------------------------------------

customer_frequency["average_days_between_orders"] = (
    customer_frequency["customer_lifetime_days"]
    / (customer_frequency["total_orders"] - 1)
).where(
    customer_frequency["total_orders"] > 1,
    0
)

# --------------------------------------------
# Activity status
# --------------------------------------------

customer_frequency["activity_status"] = pd.cut(
    customer_frequency["recency_days"],
    bins=[-1, 30, 90, 180, float("inf")],
    labels=[
        "Active",
        "Recently Inactive",
        "At Risk",
        "Inactive"
    ]
)

# --------------------------------------------
# Round values
# --------------------------------------------

customer_frequency = customer_frequency.round({
    "total_revenue": 2,
    "average_days_between_orders": 2
})

# --------------------------------------------
# Display
# --------------------------------------------

print("CUSTOMER PURCHASE FREQUENCY & RECENCY")
print("=" * 100)

print(customer_frequency.head(20))

Latest order date: 2025-12-31 00:00:00
CUSTOMER PURCHASE FREQUENCY & RECENCY
====================================================================================================
            first_order_date last_order_date  total_orders  total_revenue  \
customer_id
C00001            2025-01-01      2025-01-01             5         729.45
C00002            2025-01-01      2025-01-01            19        4105.65
C00003            2025-01-01      2025-01-01             4         561.90
C00004            2025-01-01      2025-01-01             7        1114.60
C00005            2025-01-01      2025-01-01             2         345.80
C00006            2025-01-01      2025-01-01             2         393.75
C00007            2025-01-01      2025-01-01             5        1101.95
C00008            2025-01-01      2025-01-01            11        2067.10
C00009            2025-01-01      2025-01-01             2         306.90
C00010            2025-01-01      2025-01-01             5         666.60
C00012            2025-01-01      2025-01-02             9        1211.00
C00013            2025-01-02      2025-01-02             2         420.40
C00014            2025-01-02      2025-01-02             3         669.70
C00015            2025-01-02      2025-01-02             2         230.35
C00016            2025-01-02      2025-01-02             4         798.35
C00017            2025-01-02      2025-01-02             4         744.90
C00018            2025-01-02      2025-01-02             9        1485.35
C00019            2025-01-02      2025-01-02             3         490.45
C00020            2025-01-02      2025-01-02             2         224.50
C00021            2025-01-02      2025-01-02             7        1298.65

             recency_days  customer_lifetime_days  \
customer_id
C00001                364                       0
C00002                364                       0
C00003                364                       0
C00004                364                       0
C00005                364                       0
C00006                364                       0
C00007                364                       0
C00008                364                       0
C00009                364                       0
C00010                364                       0
C00012                363                       1
C00013                363                       0
C00014                363                       0
C00015                363                       0
C00016                363                       0
C00017                363                       0
C00018                363                       0
C00019                363                       0
C00020                363                       0
C00021                363                       0

             average_days_between_orders activity_status
customer_id
C00001                              0.00        Inactive
C00002                              0.00        Inactive
C00003                              0.00        Inactive
C00004                              0.00        Inactive
C00005                              0.00        Inactive
C00006                              0.00        Inactive
C00007                              0.00        Inactive
C00008                              0.00        Inactive
C00009                              0.00        Inactive
C00010                              0.00        Inactive
C00012                              0.12        Inactive
C00013                              0.00        Inactive
C00014                              0.00        Inactive
C00015                              0.00        Inactive
C00016                              0.00        Inactive
C00017                              0.00        Inactive
C00018                              0.00        Inactive
C00019                              0.00        Inactive
C00020                              0.00        Inactive
C00021                              0.00        Inactive

In [131]:
# ============================================
# STEP 4.38 — CUSTOMER ACTIVITY SUMMARY
# ============================================

activity_summary = (
    customer_frequency
    .groupby("activity_status", observed=True)
    .agg(
        customers=("total_orders", "count"),
        total_orders=("total_orders", "sum"),
        total_revenue=("total_revenue", "sum"),
        average_orders=("total_orders", "mean"),
        average_revenue=("total_revenue", "mean"),
        average_recency_days=("recency_days", "mean")
    )
)

# --------------------------------------------
# Customer percentage
# --------------------------------------------

activity_summary["customer_percentage"] = (
    activity_summary["customers"]
    / activity_summary["customers"].sum()
    * 100
)

# --------------------------------------------
# Revenue percentage
# --------------------------------------------

activity_summary["revenue_percentage"] = (
    activity_summary["total_revenue"]
    / activity_summary["total_revenue"].sum()
    * 100
)

# --------------------------------------------
# Round
# --------------------------------------------

activity_summary = activity_summary.round({
    "average_orders": 2,
    "average_revenue": 2,
    "average_recency_days": 2,
    "customer_percentage": 2,
    "revenue_percentage": 2
})

print("CUSTOMER ACTIVITY SUMMARY")
print("=" * 100)

print(activity_summary)

CUSTOMER ACTIVITY SUMMARY
====================================================================================================
                   customers  total_orders  total_revenue  average_orders  \
activity_status
Active                   410          2488      447551.55            6.07
Recently Inactive        835          4933      774134.05            5.91
At Risk                 1223          7454     1420330.10            6.09
Inactive                2446         15125     2739465.00            6.18

                   average_revenue  average_recency_days  customer_percentage  \
activity_status
Active                     1091.59                 14.77                 8.34
Recently Inactive           927.11                 60.41                16.99
At Risk                    1161.35                135.47                24.89
Inactive                   1119.98                272.30                49.78

                   revenue_percentage
activity_status
Active                           8.32
Recently Inactive               14.39
At Risk                         26.39
Inactive                        50.91

In [132]:
# ============================================
# STEP 4.39: ORDER STATUS PERFORMANCE
# ============================================

order_status_performance = (
    orders
    .groupby("order_status")
    .agg(
        # Number of orders
        total_orders=("order_id", "count"),

        # Total revenue
        total_revenue=("order_value", "sum"),

        # Average order value
        average_order_value=("order_value", "mean"),

        # Average customer rating
        average_rating=("customer_rating", "mean")
    )
)

# --------------------------------------------
# Calculate order percentage
# --------------------------------------------

order_status_performance["order_percentage"] = (
    order_status_performance["total_orders"]
    / order_status_performance["total_orders"].sum()
    * 100
)

# --------------------------------------------
# Calculate revenue percentage
# --------------------------------------------

order_status_performance["revenue_percentage"] = (
    order_status_performance["total_revenue"]
    / order_status_performance["total_revenue"].sum()
    * 100
)

# --------------------------------------------
# Round values
# --------------------------------------------

order_status_performance = order_status_performance.round({
    "total_revenue": 2,
    "average_order_value": 2,
    "average_rating": 2,
    "order_percentage": 2,
    "revenue_percentage": 2
})

# --------------------------------------------
# Display result
# --------------------------------------------

print("ORDER STATUS PERFORMANCE")
print("=" * 100)

print(order_status_performance)

ORDER STATUS PERFORMANCE
====================================================================================================
              total_orders  total_revenue  average_order_value  \
order_status
Cancelled             1624      286917.80               176.67
Delivered            27583     4952078.75               179.53
Failed                 793      142484.15               179.68

              average_rating  order_percentage  revenue_percentage
order_status
Cancelled                NaN              5.41                5.33
Delivered               3.98             91.94               92.02
Failed                   NaN              2.64                2.65

In [133]:
# ============================================
# Step 5.1 — Check existing restaurant data
# ============================================
print(restaurant_performance.columns.tolist())

['restaurant_id', 'total_orders', 'total_revenue', 'average_order_value', 'delivered_orders', 'cancelled_orders', 'failed_orders', 'average_rating', 'cancellation_rate', 'failure_rate']

In [134]:
# ============================================
# STEP 5.2 — RESTAURANT COMPETITIVE BENCHMARKING
# ============================================

# Calculate overall market benchmarks
avg_orders = restaurant_performance["total_orders"].mean()
avg_revenue = restaurant_performance["total_revenue"].mean()
avg_rating = restaurant_performance["average_rating"].mean()
avg_aov = restaurant_performance["average_order_value"].mean()
avg_cancellation = restaurant_performance["cancellation_rate"].mean()
avg_failure = restaurant_performance["failure_rate"].mean()

# --------------------------------------------
# Create competitive position
# --------------------------------------------

competitive_benchmark = restaurant_performance.copy()

competitive_benchmark["orders_vs_market"] = (
    competitive_benchmark["total_orders"] / avg_orders * 100
)

competitive_benchmark["revenue_vs_market"] = (
    competitive_benchmark["total_revenue"] / avg_revenue * 100
)

competitive_benchmark["aov_vs_market"] = (
    competitive_benchmark["average_order_value"] / avg_aov * 100
)

competitive_benchmark["rating_vs_market"] = (
    competitive_benchmark["average_rating"] / avg_rating * 100
)

# --------------------------------------------
# Competitive classification
# --------------------------------------------

competitive_benchmark["competitive_position"] = "Average"

competitive_benchmark.loc[
    (competitive_benchmark["total_revenue"] >= avg_revenue) &
    (competitive_benchmark["average_rating"] >= avg_rating),
    "competitive_position"
] = "Strong Competitor"

competitive_benchmark.loc[
    (competitive_benchmark["total_revenue"] >= avg_revenue) &
    (competitive_benchmark["average_rating"] < avg_rating),
    "competitive_position"
] = "High Revenue / Lower Rating"

competitive_benchmark.loc[
    (competitive_benchmark["total_revenue"] < avg_revenue) &
    (competitive_benchmark["average_rating"] >= avg_rating),
    "competitive_position"
] = "Low Revenue / High Rating"

# --------------------------------------------
# Round values
# --------------------------------------------

competitive_benchmark = competitive_benchmark.round({
    "orders_vs_market": 2,
    "revenue_vs_market": 2,
    "aov_vs_market": 2,
    "rating_vs_market": 2
})

# --------------------------------------------
# Display
# --------------------------------------------

print("RESTAURANT COMPETITIVE BENCHMARKING")
print("=" * 100)

print(competitive_benchmark.head(20))

print("\nMARKET BENCHMARKS")
print("=" * 100)

print("Average orders per restaurant:", round(avg_orders, 2))
print("Average revenue per restaurant:", round(avg_revenue, 2))
print("Average AOV:", round(avg_aov, 2))
print("Average rating:", round(avg_rating, 2))
print("Average cancellation rate:", round(avg_cancellation, 2))
print("Average failure rate:", round(avg_failure, 2))

RESTAURANT COMPETITIVE BENCHMARKING
====================================================================================================
   restaurant_id  total_orders  total_revenue  average_order_value  \
0           R001           280       51878.80               185.28
1           R002            98       15156.20               154.66
2           R003           266       34434.60               129.45
3           R004           116       19722.80               170.02
4           R005           170       31159.00               183.29
5           R006            64        9716.50               151.82
6           R007            94       17222.50               183.22
7           R008           289       52625.25               182.09
8           R009            82       14029.55               171.09
9           R010            71       16400.85               231.00
10          R011           260       29883.00               114.93
11          R012            80       17499.10               218.74
12          R013           111       20707.80               186.56
13          R014           207       64864.00               313.35
14          R015           145       23019.75               158.76
15          R016           278       48213.75               173.43
16          R017           330       46446.60               140.75
17          R018           374       90556.30               242.13
18          R019           135       18539.70               137.33
19          R020           261       45281.60               173.49

    delivered_orders  cancelled_orders  failed_orders  average_rating  \
0                260                18              2            4.63
1                 89                 8              1            3.65
2                253                 9              4            4.08
3                112                 4              0            4.12
4                160                 6              4            4.79
5                 63                 1              0            3.10
6                 87                 7              0            3.67
7                277                 8              4            3.40
8                 80                 1              1            3.42
9                 64                 3              4            4.00
10               246                10              4            3.76
11                74                 6              0            3.74
12               107                 3              1            4.62
13               197                 7              3            4.63
14               137                 4              4            3.05
15               266                 8              4            3.36
16               317                10              3            4.26
17               353                15              6            3.70
18               130                 2              3            3.52
19               244                13              4            3.64

    cancellation_rate  failure_rate  orders_vs_market  revenue_vs_market  \
0                6.43          0.71             140.0             144.60
1                8.16          1.02              49.0              42.25
2                3.38          1.50             133.0              95.98
3                3.45          0.00              58.0              54.97
4                3.53          2.35              85.0              86.85
5                1.56          0.00              32.0              27.08
6                7.45          0.00              47.0              48.00
7                2.77          1.38             144.5             146.68
8                1.22          1.22              41.0              39.11
9                4.23          5.63              35.5              45.71
10               3.85          1.54             130.0              83.29
11               7.50          0.00              40.0              48.78
12               2.70          0.90              55.5              57.72
13               3.38          1.45             103.5             180.80
14               2.76          2.76              72.5              64.16
15               2.88          1.44             139.0             134.39
16               3.03          0.91             165.0             129.46
17               4.01          1.60             187.0             252.41
18               1.48          2.22              67.5              51.68
19               4.98          1.53             130.5             126.22

    aov_vs_market  rating_vs_market         competitive_position
0          101.12            119.56            Strong Competitor
1           84.41             94.26                      Average
2           70.65            105.36    Low Revenue / High Rating
3           92.79            106.39    Low Revenue / High Rating
4          100.03            123.70    Low Revenue / High Rating
5           82.86             80.05                      Average
6           99.99             94.77                      Average
7           99.38             87.80  High Revenue / Lower Rating
8           93.37             88.32                      Average
9          126.07            103.30    Low Revenue / High Rating
10          62.72             97.10                      Average
11         119.38             96.58                      Average
12         101.82            119.31    Low Revenue / High Rating
13         171.02            119.56            Strong Competitor
14          86.65             78.76                      Average
15          94.65             86.77  High Revenue / Lower Rating
16          76.82            110.01            Strong Competitor
17         132.15             95.55  High Revenue / Lower Rating
18          74.95             90.90                      Average
19          94.68             94.00  High Revenue / Lower Rating

MARKET BENCHMARKS
====================================================================================================
Average orders per restaurant: 200.0
Average revenue per restaurant: 35876.54
Average AOV: 183.23
Average rating: 3.87
Average cancellation rate: 5.81
Average failure rate: 2.67

In [135]:
# ============================================
# STEP 5.3 — COMPETITIVE POSITION DISTRIBUTION
# ============================================

competitive_summary = (
    competitive_benchmark
    .groupby("competitive_position")
    .agg(
        restaurants=("restaurant_id", "count"),
        total_orders=("total_orders", "sum"),
        total_revenue=("total_revenue", "sum"),
        average_order_value=("average_order_value", "mean"),
        average_rating=("average_rating", "mean"),
        average_cancellation_rate=("cancellation_rate", "mean"),
        average_failure_rate=("failure_rate", "mean")
    )
)

# --------------------------------------------
# Restaurant percentage
# --------------------------------------------

competitive_summary["restaurant_percentage"] = (
    competitive_summary["restaurants"]
    / competitive_summary["restaurants"].sum()
    * 100
)

# --------------------------------------------
# Revenue percentage
# --------------------------------------------

competitive_summary["revenue_percentage"] = (
    competitive_summary["total_revenue"]
    / competitive_summary["total_revenue"].sum()
    * 100
)

# --------------------------------------------
# Round values
# --------------------------------------------

competitive_summary = competitive_summary.round({
    "total_revenue": 2,
    "average_order_value": 2,
    "average_rating": 2,
    "average_cancellation_rate": 2,
    "average_failure_rate": 2,
    "restaurant_percentage": 2,
    "revenue_percentage": 2
})

# --------------------------------------------
# Display
# --------------------------------------------

print("COMPETITIVE POSITION DISTRIBUTION")
print("=" * 100)

print(competitive_summary)

COMPETITIVE POSITION DISTRIBUTION
====================================================================================================
                             restaurants  total_orders  total_revenue  \
competitive_position
Average                               54          6629     1137066.30
High Revenue / Lower Rating           20          5672     1078934.95
Low Revenue / High Rating             37          5302      883237.10
Strong Competitor                     39         12397     2282242.35

                             average_order_value  average_rating  \
competitive_position
Average                                   175.26            3.41
High Revenue / Lower Rating               196.40            3.44
Low Revenue / High Rating                 174.22            4.25
Strong Competitor                         196.06            4.38

                             average_cancellation_rate  average_failure_rate  \
competitive_position
Average                                           6.04                  2.44
High Revenue / Lower Rating                       4.48                  2.16
Low Revenue / High Rating                         7.14                  3.37
Strong Competitor                                 4.91                  2.59

                             restaurant_percentage  revenue_percentage
competitive_position
Average                                      36.00               21.13
High Revenue / Lower Rating                  13.33               20.05
Low Revenue / High Rating                    24.67               16.41
Strong Competitor                            26.00               42.41

In [136]:
# ============================================
# STEP 5.4 — RESTAURANT COMPETITIVE OPPORTUNITIES
# ============================================

competitive_opportunities = competitive_benchmark[
    competitive_benchmark["competitive_position"] != "Average"
].copy()

# Sort by revenue to identify commercially important restaurants
competitive_opportunities = (
    competitive_opportunities
    .sort_values("total_revenue", ascending=False)
)

print("RESTAURANT COMPETITIVE OPPORTUNITIES")
print("=" * 100)

print(
    competitive_opportunities[
        [
            "restaurant_id",
            "total_orders",
            "total_revenue",
            "average_order_value",
            "average_rating",
            "cancellation_rate",
            "failure_rate",
            "competitive_position"
        ]
    ].head(30)
)

RESTAURANT COMPETITIVE OPPORTUNITIES
====================================================================================================
    restaurant_id  total_orders  total_revenue  average_order_value  \
55           R056           591      150095.50               253.97
73           R074           574      105662.70               184.08
92           R093           317      101035.70               318.72
17           R018           374       90556.30               242.13
95           R096           444       84598.25               190.54
138          R139           427       84359.20               197.56
63           R064           215       75528.00               351.29
36           R037           405       72627.70               179.33
110          R111           436       70884.80               162.58
47           R048           228       70039.55               307.19
80           R081           222       68832.00               310.05
115          R116           197       67734.00               343.83
23           R024           477       67712.60               141.96
70           R071           348       66738.95               191.78
136          R137           479       66703.60               139.26
120          R121           205       66568.35               324.72
13           R014           207       64864.00               313.35
24           R025           386       63636.10               164.86
43           R044           356       61130.00               171.71
31           R032           319       60121.05               188.47
32           R033           330       57231.60               173.43
117          R118           199       57093.65               286.90
99           R100           339       56198.25               165.78
41           R042           319       56179.70               176.11
137          R138           306       55473.80               181.29
135          R136           244       55289.00               226.59
66           R067           382       53379.80               139.74
65           R066           335       52849.40               157.76
57           R058           262       52705.80               201.17
7            R008           289       52625.25               182.09

     average_rating  cancellation_rate  failure_rate  \
55             4.53               4.06          1.69
73             4.58               2.61          3.14
92             4.70               3.47          1.58
17             3.70               4.01          1.60
95             4.48               4.95          2.03
138            4.69              13.82          8.20
63             3.11               4.19          2.33
36             4.58               2.96          2.22
110            4.69               2.52          1.83
47             3.15               1.32          2.19
80             3.94               3.60          1.35
115            4.32               2.54          2.03
23             4.26               3.56          1.47
70             3.76               4.31          2.30
136            4.29              12.11          6.89
120            4.19               3.41          0.98
13             4.63               3.38          1.45
24             4.13               5.70          1.81
43             4.76               3.93          2.25
31             4.14               3.45          2.19
32             3.39               4.85          1.52
117            3.17               4.52          1.51
99             4.22               4.72          2.06
41             3.63               3.76          1.25
137            3.73              16.67          8.17
135            3.89              12.70          7.79
66             4.33               4.19          1.57
65             3.82               3.28          2.39
57             3.74               3.82          3.05
7              3.40               2.77          1.38

            competitive_position
55             Strong Competitor
73             Strong Competitor
92             Strong Competitor
17   High Revenue / Lower Rating
95             Strong Competitor
138            Strong Competitor
63   High Revenue / Lower Rating
36             Strong Competitor
110            Strong Competitor
47   High Revenue / Lower Rating
80             Strong Competitor
115            Strong Competitor
23             Strong Competitor
70   High Revenue / Lower Rating
136            Strong Competitor
120            Strong Competitor
13             Strong Competitor
24             Strong Competitor
43             Strong Competitor
31             Strong Competitor
32   High Revenue / Lower Rating
117  High Revenue / Lower Rating
99             Strong Competitor
41   High Revenue / Lower Rating
137  High Revenue / Lower Rating
135            Strong Competitor
66             Strong Competitor
65   High Revenue / Lower Rating
57   High Revenue / Lower Rating
7    High Revenue / Lower Rating

In [137]:
# ============================================
# STEP 6.1: PEAK DEMAND OPPORTUNITY ANALYSIS
# ============================================

# --------------------------------------------
# Monthly peak demand
# --------------------------------------------

peak_month = (
    orders.groupby("month_name")
    .agg(
        total_orders=("order_id", "count"),
        total_revenue=("order_value", "sum"),
        average_order_value=("order_value", "mean")
    )
    .sort_values("total_orders", ascending=False)
    .head(5)
    .round(2)
)

print("TOP 5 MONTHS BY ORDER DEMAND")
print("=" * 100)
print(peak_month)


# --------------------------------------------
# Day-of-week peak demand
# --------------------------------------------

peak_days = (
    orders.groupby("day_name")
    .agg(
        total_orders=("order_id", "count"),
        total_revenue=("order_value", "sum"),
        average_order_value=("order_value", "mean")
    )
    .sort_values("total_orders", ascending=False)
    .round(2)
)

print("\nDAY-OF-WEEK DEMAND RANKING")
print("=" * 100)
print(peak_days)


# --------------------------------------------
# Meal-period peak demand
# --------------------------------------------

peak_meals = (
    orders.groupby("meal_period")
    .agg(
        total_orders=("order_id", "count"),
        total_revenue=("order_value", "sum"),
        average_order_value=("order_value", "mean")
    )
    .sort_values("total_orders", ascending=False)
    .round(2)
)

print("\nMEAL PERIOD DEMAND RANKING")
print("=" * 100)
print(peak_meals)

TOP 5 MONTHS BY ORDER DEMAND
====================================================================================================
            total_orders  total_revenue  average_order_value
month_name
August              2626      515076.25               196.14
May                 2626      469492.95               178.79
January             2571      430483.95               167.44
March               2570      480129.20               186.82
July                2569      507796.75               197.66

DAY-OF-WEEK DEMAND RANKING
====================================================================================================
           total_orders  total_revenue  average_order_value
day_name
Saturday           5377      958259.05               178.21
Sunday             4989      897766.45               179.95
Friday             4515      806217.90               178.56
Thursday           3958      706239.30               178.43
Wednesday          3944      711427.65               180.38
Tuesday            3637      656721.55               180.57
Monday             3580      644848.80               180.13

MEAL PERIOD DEMAND RANKING
====================================================================================================
             total_orders  total_revenue  average_order_value
meal_period
Dinner              12558     2183408.00               173.87
Lunch                8449     1548057.65               183.22
Breakfast            5254      910014.30               173.20
Evening              3739      740000.75               197.91

In [138]:
# ============================================
# STEP 7.1: ORDER VALUE / PRICING ANALYSIS
# ============================================

pricing_analysis = (
    orders.groupby("ordered_cuisine")
    .agg(
        total_orders=("order_id", "count"),
        total_revenue=("order_value", "sum"),
        average_order_value=("order_value", "mean"),
        median_order_value=("order_value", "median")
    )
    .sort_values("average_order_value", ascending=False)
    .round(2)
)

print("CUISINE PRICING ANALYSIS")
print("=" * 100)
print(pricing_analysis)

CUISINE PRICING ANALYSIS
====================================================================================================
                 total_orders  total_revenue  average_order_value  \
ordered_cuisine
Pizza                    3619     1059515.60               292.76
Healthy                  2875      546173.85               189.97
Biryani                  3661      694912.50               189.81
Burgers                  2114      372244.55               176.09
North Indian             5403      932745.00               172.63
Chinese                  3256      531739.40               163.31
Momos                    1997      322190.15               161.34
Desserts                 2041      312286.55               153.01
Cafe                     1343      184008.85               137.01
South Indian             3691      425664.25               115.32

                 median_order_value
ordered_cuisine
Pizza                        310.95
Healthy                      185.75
Biryani                      185.75
Burgers                      168.70
North Indian                 174.00
Chinese                      164.60
Momos                        160.20
Desserts                     152.20
Cafe                         132.20
South Indian                 110.00

In [139]:
# ============================================
# STEP 7.2: ORDER VALUE PRICE BAND ANALYSIS
# ============================================

orders["price_band"] = pd.cut(
    orders["order_value"],
    bins=[0, 100, 150, 200, 250, 300, float("inf")],
    labels=[
        "Below 100",
        "100-150",
        "150-200",
        "200-250",
        "250-300",
        "300+"
    ],
    include_lowest=True
)

price_band_analysis = (
    orders.groupby("price_band", observed=False)
    .agg(
        total_orders=("order_id", "count"),
        total_revenue=("order_value", "sum"),
        average_order_value=("order_value", "mean")
    )
)

# Add percentages
price_band_analysis["order_percentage"] = (
    price_band_analysis["total_orders"]
    / price_band_analysis["total_orders"].sum() * 100
)

price_band_analysis["revenue_percentage"] = (
    price_band_analysis["total_revenue"]
    / price_band_analysis["total_revenue"].sum() * 100
)

price_band_analysis = price_band_analysis.round(2)

print("ORDER VALUE PRICE BAND ANALYSIS")
print("=" * 100)
print(price_band_analysis)

ORDER VALUE PRICE BAND ANALYSIS
====================================================================================================
            total_orders  total_revenue  average_order_value  \
price_band
Below 100           2562      227837.75                88.93
100-150             8682     1107193.85               127.53
150-200            10312     1791854.50               173.76
200-250             4119      904943.45               219.70
250-300             2056      557508.50               271.16
300+                2269      792142.65               349.12

            order_percentage  revenue_percentage
price_band
Below 100               8.54                4.23
100-150                28.94               20.57
150-200                34.37               33.30
200-250                13.73               16.82
250-300                 6.85               10.36
300+                    7.56               14.72

## Locality Opportunity Score Methodology

The locality opportunity score was developed to compare potential cloud-kitchen locations using seven factors related to market potential, customer fit, and competition. Each factor was assigned a weight based on its expected importance for evaluating a new cloud-kitchen location.

| Factor | Weight | Rationale |
|---|---:|---|
| Population Density | 20% | Higher population density indicates a larger potential customer base within the delivery area. |
| Average Monthly Income | 20% | Higher income levels can support greater food-delivery spending and higher-value orders. |
| Student Share | 10% | Students represent an important target segment for affordable and convenient food delivery. |
| Office Worker Share | 15% | Office workers can generate consistent weekday lunch and dinner demand. |
| Residential Share | 10% | Higher residential concentration supports recurring household delivery demand. |
| Tourism Score | 10% | Tourism can provide additional demand, although it may be less consistent than residential or working-population demand. |
| Low Competition | 15% | Lower competition provides a better opportunity for a new cloud kitchen to enter and establish market presence. |
| **Total** | **100%** | |

In [140]:
# ============================================
# STEP 8.1: LOCALITY OPPORTUNITY SCORING
# ============================================

locality_opportunity = localities.copy()

# Normalize positive opportunity factors to 0–100
def min_max_score(series):
    return (
        (series - series.min()) /
        (series.max() - series.min()) * 100
    )

locality_opportunity["density_score"] = min_max_score(
    locality_opportunity["population_density"]
)

locality_opportunity["income_score"] = min_max_score(
    locality_opportunity["avg_monthly_income"]
)

locality_opportunity["student_score"] = min_max_score(
    locality_opportunity["student_share_pct"]
)

locality_opportunity["office_score"] = min_max_score(
    locality_opportunity["office_worker_share_pct"]
)

locality_opportunity["residential_score"] = min_max_score(
    locality_opportunity["residential_share_pct"]
)

locality_opportunity["tourism_score_normalized"] = min_max_score(
    locality_opportunity["tourism_score"]
)

# Lower competition is better for a new entrant
locality_opportunity["competition_opportunity_score"] = (
    100 - min_max_score(locality_opportunity["competition_score"])
)

# --------------------------------------------
# Weighted opportunity score
# --------------------------------------------

locality_opportunity["opportunity_score"] = (
    locality_opportunity["density_score"] * 0.20 +
    locality_opportunity["income_score"] * 0.20 +
    locality_opportunity["student_score"] * 0.10 +
    locality_opportunity["office_score"] * 0.15 +
    locality_opportunity["residential_score"] * 0.10 +
    locality_opportunity["tourism_score_normalized"] * 0.10 +
    locality_opportunity["competition_opportunity_score"] * 0.15
)

# Rank localities
locality_opportunity["opportunity_rank"] = (
    locality_opportunity["opportunity_score"]
    .rank(ascending=False, method="min")
    .astype(int)
)

# Round values
locality_opportunity = locality_opportunity.round(2)

# Sort by opportunity
locality_opportunity = locality_opportunity.sort_values(
    "opportunity_score",
    ascending=False
)

print("LOCALITY OPPORTUNITY SCORING")
print("=" * 100)

print(
    locality_opportunity[
        [
            "locality_name",
            "zone",
            "population_density",
            "avg_monthly_income",
            "student_share_pct",
            "office_worker_share_pct",
            "tourism_score",
            "competition_score",
            "opportunity_score",
            "opportunity_rank"
        ]
    ]
)

LOCALITY OPPORTUNITY SCORING
====================================================================================================
        locality_name     zone  population_density  avg_monthly_income  \
0         Rajpur Road  Central                  82               52000
5        Vasant Vihar     West                  64               51000
4            Ballupur  Central                  85               45000
1              Jakhan    North                  76               48000
9         Race Course  Central                  86               43000
8        Nehru Colony  Central                  91               39000
7  Sahastradhara Road     East                  60               47000
6         Patel Nagar  Central                  88               37000
2        Clement Town    South                  68               36000
3          Prem Nagar     West                  72               33000

   student_share_pct  office_worker_share_pct  tourism_score  \
0                 12                       32             85
5                 10                       35             40
4                 18                       30             62
1                 15                       28             78
9                 12                       30             55
8                 16                       28             38
7                 22                       25             70
6                 14                       22             30
2                 28                       18             45
3                 32                       16             35

   competition_score  opportunity_score  opportunity_rank
0                 88              62.73                 1
5                 52              61.85                 2
4                 76              57.10                 3
1                 80              57.09                 4
9                 73              55.27                 5
8                 70              55.05                 6
7                 64              48.57                 7
6                 58              46.75                 8
2                 55              34.85                 9
3                 48              33.65                10

## Location Scoring Insight

Rajpur Road achieved the highest raw opportunity score at 62.73, followed by Vasant Vihar at 61.85. However, the final launch recommendation was not based on the opportunity score alone.

The final decision score combined the locality opportunity score (50%) with market attractiveness (50%). Market attractiveness incorporated demand potential, customer fit, tourism potential, and competitive conditions.

Based on this combined assessment, Vasant Vihar achieved the highest overall decision score of 64.38, compared with 62.20 for Rajpur Road.

Therefore, Vasant Vihar was selected as the recommended launch location because it provides a stronger overall balance between opportunity and market attractiveness.

In [141]:
# ============================================
# STEP 8.2: TOP LOCATION SHORTLIST
# ============================================

top_locations = (
    locality_opportunity
    .sort_values("opportunity_score", ascending=False)
    .head(5)
    .copy()
)

print("TOP 5 LOCATION SHORTLIST")
print("=" * 100)

print(
    top_locations[
        [
            "locality_name",
            "zone",
            "population_density",
            "avg_monthly_income",
            "student_share_pct",
            "office_worker_share_pct",
            "residential_share_pct",
            "tourism_score",
            "competition_score",
            "opportunity_score",
            "opportunity_rank"
        ]
    ].to_string(index=False)
)

TOP 5 LOCATION SHORTLIST
====================================================================================================
locality_name    zone  population_density  avg_monthly_income  student_share_pct  office_worker_share_pct  residential_share_pct  tourism_score  competition_score  opportunity_score  opportunity_rank
  Rajpur Road Central                  82               52000                 12                       32                     42             85                 88              62.73                 1
 Vasant Vihar    West                  64               51000                 10                       35                     48             40                 52              61.85                 2
     Ballupur Central                  85               45000                 18                       30                     40             62                 76              57.10                 3
       Jakhan   North                  76               48000                 15                       28                     45             78                 80              57.09                 4
  Race Course Central                  86               43000                 12                       30                     43             55                 73              55.27                 5

In [142]:
# ============================================
# STEP 8.3: DEMAND OPPORTUNITY SUMMARY
# ============================================

print("DEMAND OPPORTUNITY SUMMARY")
print("=" * 100)

print("\nTOP DEMAND MONTHS")
print("""
August    - 2,626 orders | AOV: 196.14
May       - 2,626 orders | AOV: 178.79
January   - 2,571 orders | AOV: 167.44
March     - 2,570 orders | AOV: 186.82
July      - 2,569 orders | AOV: 197.66
""")

print("\nTOP DEMAND DAYS")
print("""
Saturday  - 5,377 orders | Revenue: 958,259.05
Sunday    - 4,989 orders | Revenue: 897,766.45
Friday    - 4,515 orders | Revenue: 806,217.90
""")

print("\nMEAL PERIOD OPPORTUNITY")
print("""
Dinner   - 12,558 orders | Revenue: 2,183,408.00
Lunch    -  8,449 orders | Revenue: 1,548,057.65
Evening  -  3,739 orders | AOV: 197.91
""")

print("\nCUISINE OPPORTUNITY")
print("""
Pizza          - AOV: 292.76 | Revenue: 1,059,515.60
Biryani        - AOV: 189.81 | Revenue:   694,912.50
Healthy        - AOV: 189.97 | Revenue:   546,173.85
North Indian   - AOV: 172.63 | Revenue:   932,745.00
""")

print("\nPRICE BAND OPPORTUNITY")
print("""
150-200  - 34.37% of orders | 33.30% of revenue
100-150  - 28.94% of orders | 20.57% of revenue
200-250  - 13.73% of orders | 16.82% of revenue
300+     -  7.56% of orders | 14.72% of revenue
""")

DEMAND OPPORTUNITY SUMMARY
====================================================================================================

TOP DEMAND MONTHS

August    - 2,626 orders | AOV: 196.14
May       - 2,626 orders | AOV: 178.79
January   - 2,571 orders | AOV: 167.44
March     - 2,570 orders | AOV: 186.82
July      - 2,569 orders | AOV: 197.66


TOP DEMAND DAYS

Saturday  - 5,377 orders | Revenue: 958,259.05
Sunday    - 4,989 orders | Revenue: 897,766.45
Friday    - 4,515 orders | Revenue: 806,217.90


MEAL PERIOD OPPORTUNITY

Dinner   - 12,558 orders | Revenue: 2,183,408.00
Lunch    -  8,449 orders | Revenue: 1,548,057.65
Evening  -  3,739 orders | AOV: 197.91


CUISINE OPPORTUNITY

Pizza          - AOV: 292.76 | Revenue: 1,059,515.60
Biryani        - AOV: 189.81 | Revenue:   694,912.50
Healthy        - AOV: 189.97 | Revenue:   546,173.85
North Indian   - AOV: 172.63 | Revenue:   932,745.00


PRICE BAND OPPORTUNITY

150-200  - 34.37% of orders | 33.30% of revenue
100-150  - 28.94% of orders | 20.57% of revenue
200-250  - 13.73% of orders | 16.82% of revenue
300+     -  7.56% of orders | 14.72% of revenue

In [143]:
# ============================================
# STEP 8.4: LOCATION × BUSINESS CONCEPT
# DECISION MATRIX
# ============================================

# Take top 5 shortlisted locations
decision_matrix = locality_opportunity[
    locality_opportunity["opportunity_rank"] <= 5
].copy()

# --------------------------------------------
# Demand potential
# --------------------------------------------

decision_matrix["demand_potential"] = (
    decision_matrix["density_score"] * 0.40 +
    decision_matrix["office_score"] * 0.30 +
    decision_matrix["residential_score"] * 0.30
)

# --------------------------------------------
# Customer fit
# --------------------------------------------

decision_matrix["customer_fit"] = (
    decision_matrix["income_score"] * 0.40 +
    decision_matrix["student_score"] * 0.20 +
    decision_matrix["office_score"] * 0.40
)

# --------------------------------------------
# Market attractiveness
# --------------------------------------------

decision_matrix["market_attractiveness"] = (
    decision_matrix["demand_potential"] * 0.35 +
    decision_matrix["customer_fit"] * 0.30 +
    decision_matrix["tourism_score_normalized"] * 0.15 +
    decision_matrix["competition_opportunity_score"] * 0.20
)

# --------------------------------------------
# Overall decision score
# --------------------------------------------

decision_matrix["decision_score"] = (
    decision_matrix["opportunity_score"] * 0.50 +
    decision_matrix["market_attractiveness"] * 0.50
)

# Rank
decision_matrix["decision_rank"] = (
    decision_matrix["decision_score"]
    .rank(ascending=False, method="min")
    .astype(int)
)

# Round
decision_matrix = decision_matrix.round(2)

# Sort
decision_matrix = decision_matrix.sort_values(
    "decision_score",
    ascending=False
)

print("LOCATION × BUSINESS CONCEPT DECISION MATRIX")
print("=" * 100)

print(
    decision_matrix[
        [
            "locality_name",
            "zone",
            "demand_potential",
            "customer_fit",
            "competition_score",
            "market_attractiveness",
            "opportunity_score",
            "decision_score",
            "decision_rank"
        ]
    ].to_string(index=False)
)

LOCATION × BUSINESS CONCEPT DECISION MATRIX
====================================================================================================
locality_name    zone  demand_potential  customer_fit  competition_score  market_attractiveness  opportunity_score  decision_score  decision_rank
 Vasant Vihar    West             65.16         77.90                 52                  66.90              61.85           64.38              1
  Rajpur Road Central             68.65         75.50                 88                  61.68              62.73           62.20              2
       Jakhan   North             62.09         61.39                 80                  57.24              57.09           57.16              3
     Ballupur Central             64.36         62.01                 76                  55.86              57.10           56.48              4
  Race Course Central             73.15         52.34                 73                  55.62              55.27           55.45              5

In [144]:
# ============================================
# STEP 10.1: EXPORT CORE DATASETS FOR SQL SERVER
# ============================================

# Export the 5 core project tables as CSV files

localities.to_csv("localities.csv", index=False)
restaurants.to_csv("restaurants.csv", index=False)
menu_items.to_csv("menu_items.csv", index=False)
customers.to_csv("customers.csv", index=False)
orders.to_csv("orders.csv", index=False)

print("SQL export files created successfully!")
print("\nFiles:")
print("1. localities.csv")
print("2. restaurants.csv")
print("3. menu_items.csv")
print("4. customers.csv")
print("5. orders.csv")

SQL export files created successfully!

Files:
1. localities.csv
2. restaurants.csv
3. menu_items.csv
4. customers.csv
5. orders.csv